### ISSUE TITLE
Is it possible to show only some features from openstreetmap ?

### ISSUE THREAD

**Issue by paapu88** [fleaflet/flutter_map#1046]
Hei, 
Is there an easy way to show a map with only certain features shown on the map with openstreetmap data? For instance, can I show a map with only cycling ways shown and nothing else? 
terveisin, Markus

**Comment by JaffaKetchup** [comment]
Hi there,
No, this is not possible and will never be possible because it is not the responsibility of a map display package (such as this one) to do that.
To do this, you'll have to make your own map source. Doing this on your own is extremely resource intensive, so I'd recommend something like Mapbox. You can create custom map 'styles' and then share them to get a URL you can use here.
Hope this helped!

**Comment by ibrierley** [comment]
Feels like a bit of a blunt response...I think it kind of depends exactly what you mean by showing "nothing else", if you need to customise, or not. For example there are cycle maps from openstreet data, eg here is a tile example https://c.tile-cyclosm.openstreetmap.fr/cyclosm/11/1025/687.png at https://www.cyclosm.org/#map=11/50.8623/-0.0439/cyclosm
Theoretically you could also display vector tiles with just a cycleway (or other) feature set, but it's probably a fair bit of work to get there.

**Comment by JaffaKetchup** [comment]
@paapu88 Sorry if I did come across a little blunt, I just wanted to be 'to the point' to point you in the right direction quicker :)

**Comment by paapu88** [comment]
Thanks, my question was badly formulated. I would be happy just writing extra lines on top of openstreetmap as pointed out by @ibrierley . cyclosm (with open source code) looks just what I was searching, thanks!
