### ISSUE TITLE
Plugin Maintenance and Updations

### ISSUE THREAD

**Issue by hiteshgarg002** [fleaflet/flutter_map#1109]
Hi, 

I am planning to use this package in one of my important projects but seems like its been 3 months since this package was updated.
So is this package still being maintained for the future flutter versions or not?

**Comment by JaffaKetchup** [comment]
I wouldn't call this project 'dead', but certainly the owner is hardly ever around and the maintainer(s) don't seem to be around much. Hopefully one can come back, because when they do, they are quite efficient.

**Comment by ibrierley** [comment]
I can't speak for others, but my gut instinct is that important updates (recent example nullsafety) would get updated. But from a design perspective I would try and amend things where possible with plugins than you can affect yourself, as you may be waiting a long time otherwise.

Naturally one can always fork the repo and update (and if there were important updates that weren't being done, I suspect this would happen whatever).
