### ISSUE TITLE
Zoom using touchpad on web is very sensitive.

### ISSUE THREAD

**Issue by joranmulderij** [fleaflet/flutter_map#1128]
When using the touch pad to zoom in and out makes the map zoom in and out by a lot. Apart from that the map works fine on web.

**Comment by JaffaKetchup** [comment]
Not sure if Flutter gives that much control over mouse input.
Touchpads are usually much more sensitive because they are smaller, and depending on the design of your touchpad, may be designed to be able to scroll all the way to the bottom of a page in one go - a map is infinite-ish.

Perhaps measuring the delay between inputs would allow the library to normalise the scrolling speed?
