### ISSUE TITLE
How to implement this style -- Arrow PolyLine

### ISSUE THREAD

**Issue by Huanxin1997** [fleaflet/flutter_map#1133]
If I can implement this style with this plugin? I need to draw the route with arrow.
![image](https://user-images.githubusercontent.com/42678103/149863126-ac9506b6-2fc3-4dea-a07a-f4f4b5796b15.png)

**Comment by JaffaKetchup** [comment]
This is unfortunately not possible at the moment, and would be complicated to implement.
Consider using appropriate markers placed along the route?

**Comment by JaffaKetchup** [comment]
Hi there @Huanxin1997,
Do you still require support? Happy to help!

**Comment by JaffaKetchup** [comment]
@Huanxin1997 Hello,
Thanks for this feature request, however we are unlikely to be adding features to this package at the moment, especially ones with workarounds. This is due to a backlog of bug reports, which must take priority.
If you feel you can write it yourself, consider creating a plugin.
I hope you understand this, but please feel free to engage more with the 'flutter_map' project - it's always nice to see activity!
Thanks once again.

**Comment by Huanxin1997** [comment]
I have implemented this style in my project in February. I'm very happy to contribute to you. If I am free, I can modify the previous code to make it more common to other users.

**Comment by mohammedX6** [comment]
@Huanxin1997  Hi, Can you please share some?

**Comment by JaffaKetchup** [comment]
Sorry @Huanxin1997, didn't see your last comment here.

We'd love to have a plugin for this if you have the spare time! Plugins are always useful and always appreciated by us and the community.
As an alternative we are happy to accept PRs, but there may be a long wait time on time kind of addition as there is potential for expansion in the future, so we'd be looking for a more customisable, bare-bones API. At the moment, I would recommend a plugin.

Just ping me here or on Discord if you need some help or when you want to add it to the docs.

Many thanks :)
