### ISSUE TITLE
Map taking too long to load when navigating

### ISSUE THREAD

**Issue by Flokart** [fleaflet/flutter_map#1138]
I want to take a screenshot of the user created markers on the map. My specific use case requires an automatic zoomOut to fit the markers inside the screenshot. The problem with that is that the screenshot is usually taken before the map is completely loaded on the sides after zooming out. I was thinking if there's any way to pre-load a larger portion of the map beforehand.  I'm using the "screenshot" package. It usually takes even longer than in the video to load but the screenshot is almost always taken like in the video unless I add a hardcoded delay which wouldn't be the best solution UX-wise. Thank you!

https://user-images.githubusercontent.com/25905620/150746215-3be12082-1ab8-463a-8cb5-a08495c5b03b.mp4

**Comment by JaffaKetchup** [comment]
Caching may help (see plugins list), but at the moment, there is no way to load parts of the map manually, without a custom TileLayer.

**Comment by ibrierley** [comment]
Just trying to understand a bit...how far in advance do you know the area, when you are creating the route type thing and not before that..its not quite clear from the video what is causing the screenshot ?

If it's fairly instant (because you just loaded up a set of checkpoints you didn't know beforehand), then I'm not sure I see any way around it, other than adding a delay before a screenshot ? One way or another it needs some time to load in the tiles...

However, hacky thought....let's say you are busy adding checkpoints and are in "checkpoint/edit mode" only, which takes some time, and then want to click the save button...

Could you create a background tile_layer, which is hidden behind the main map (so earlier in the order, or even in an Offstage widget..I guess be careful of a transparent not loaded top tile), with a maxZoom and minZoom the same, eg hidden layer is zoom 13, edit top layer is zoom 15. That way, the tiles at a different zoom level "may" have been pulled in remotely and cached by the system or by some caching tile provider (if it can share cached files between different layers).

**Comment by Flokart** [comment]
> Caching may help (see plugins list), but at the moment, there is no way to load parts of the map manually, without a custom TileLayer.

Unfortunately "flutter_map_tile_caching" requires the version 0.13.1 of "flutter_map", and there's functionality I need from the 0.14.0 version so I can not downgrade

**Comment by Flokart** [comment]
> Just trying to understand a bit...how far in advance do you know the area, when you are creating the route type thing and not before that..its not quite clear from the video what is causing the screenshot ?
> 
> If it's fairly instant (because you just loaded up a set of checkpoints you didn't know beforehand), then I'm not sure I see any way around it, other than adding a delay before a screenshot ? One way or another it needs some time to load in the tiles...
> 
> However, hacky thought....let's say you are busy adding checkpoints and are in "checkpoint/edit mode" only, which takes some time, and then want to click the save button...
> 
> Could you create a background tile_layer, which is hidden behind the main map (so earlier in the order, or even in an Offstage widget..I guess be careful of a transparent not loaded top tile), with a maxZoom and minZoom the same, eg hidden layer is zoom 13, edit top layer is zoom 15. That way, the tiles at a different zoom level "may" have been pulled in remotely and cached by the system or by some caching tile provider (if it can share cached files between different layers).

Actually the checkpoints are created by the user itself I just didn't include the whole process of creation in the video. The functionality goes like this
   1. Select initial and finish point
   2. Use third party API to draw the path between selected points
   3. OnSubmit: call fitBounds with the selected points as arguments, and then screenshot to save the created course as a picture. (The part where the problem is appearing - FitBounds triggered and screenshot created before the map is loaded)
   
I'll try the solution you mentioned and just hope it's not a heavyweight one :).
