### ISSUE TITLE
Pauses between animation

### ISSUE THREAD

**Issue by Farrukh1198** [fleaflet/flutter_map#1152]
I use animation map with Tweens. Animation controller requires duration of animation. Setting duration I get interruptions or pauses between animation. How to avoid these pauses and get smooth map moving and rotation?

**Comment by ibrierley** [comment]
I think you need to show some code, and possibly a video or something, as it's not clear on what the problem is.

**Comment by Farrukh1198** [comment]
https://user-images.githubusercontent.com/98464696/152677511-9d8ef9fa-082f-44c5-8797-92c80e24d15d.mp4

**Comment by Farrukh1198** [comment]
https://user-images.githubusercontent.com/98464696/152677653-55ec9203-7661-433a-b451-55060c447c68.mp4

After every animation was completed there is some pause because I specified required parameter duration to 200 ms (even if I set it to 500 or 1000 ms it has interruptions). Next animation begins after that pause.

**Comment by Farrukh1198** [comment]
https://user-images.githubusercontent.com/98464696/152677731-6d908cd5-89f3-474a-9f1d-cd9f25305d00.mp4

I need something like this without being interrupted.

**Comment by Farrukh1198** [comment]
https://user-images.githubusercontent.com/98464696/152677761-4aa23888-ec24-491f-85aa-823f1c0497ed.mp4

I need something like this without being interrupted

**Comment by JaffaKetchup** [comment]
Hi there @Farrukh1198,

I was also trying to achieve this at one point, but it's very difficult to do.
AFAIK, this is due to limitations with GPS. As GPS is a poll based system (not an event based one), the device must request it's location every 𝓍 seconds. Therefore, you can only animate every 𝓍 seconds, leading to starting-stopping animations like this, no matter the animation duration.

I'm not sure how other apps do it. As far as I can see in Google Maps app, the same thing happens, unless you are in navigation mode, where it somehow predicts your future movements to make it smooth. You can see this in action when navigating around a roundabout. Say the route exists on the 3rd branch, but you make a mistake and exit on the 2nd, it takes the app a little while to notice, in which the car icon keeps going around the roundabout along the route. _I'm assuming on your second video, you used an emulator with a pre-set route. This triggers the device fake GPS to poll much quicker than usual, hence why you see this._

Perhaps if you can gauge the speed, you can predict like this, but it will never be 100% accurate. If you can find a way to make it work, I'd love to know how!

**Comment by Farrukh1198** [comment]
> 

Hello. It's not about how does GPS work. It's about how does this plugin work. In the second video there are no emulators or simulations, its navigation using users current location. It's JS implementation. Now I need to do it with native tools. In JS there is no required parameter duration. 
In fact, GPS data arrives intermittently in less than a second. And in JS, the next animation knocks down the previous one, thereby preventing a pause between them.

**Comment by JaffaKetchup** [comment]
Maybe leaflet is using something else behind the scenes? Also what 'duration' are you talking about?

**Comment by ibrierley** [comment]
I think this should be possible to do (but possibly not part of flutter_map internally, as I think some of it relies on gps I assume...). I'm assuming here that it's "live" (it's easy if its recorded), in which case I'm also assuming the gps is probably having a 1 second update. I'm not sure a lot of mobiles or whatever update more than that, but I may be wrong....

So assuming you are ok with a maximum of one second lag (which seems reasonable), you can interpolate between the last 2 points (or you can probably smooth it out a bit more if you are ok with slightly longer lag and variation in gps points).

Just out of interest, I have a line_animator plugin at https://github.com/ibrierley/line_animator it's not really designed for simple 2 point interpolation (it may well work ok for that though as it just interpolates through points, but I don't really have time to go into the code if it needed modifying).
