### ISSUE TITLE
Performance issues and fatal crashes caused by WMS layer

### ISSUE THREAD

**Issue by UsamaAndroid** [fleaflet/flutter_map#1161]
Verification of void com.google.android.gms.common.api.internal.zacp.() took 123.523ms or Skipped 161 frames! The application may be doing too much work on its main thread. before app crashes andoid studio shows one of these but mostly it gives me skipped frames error in run window of android studio and finally app crashes(closed).

**Comment by UsamaAndroid** [comment]
Verification of void com.google.android.gms.common.api.internal.zacp.<clinit>() took 123.523ms    or   Skipped 161 frames! The application may be doing too much work on its main thread.  before app crashes andoid studio shows one of these but mostly it gives me skipped frames error in run window of android studio and finally app crashes(closed).

**Comment by JaffaKetchup** [comment]
Hi @UsamaAndroid,
Can I ask why you closed this? Did you resolve your issue?
Thanks.

**Comment by JaffaKetchup** [comment]
No problem. I just reopened this one though for you.

**Comment by JaffaKetchup** [comment]
Yeah no problem.

At the moment, I can't really help too much. This seems to be one of many fatal performance issues, which do need to be fixed urgently. Unfortunately, I am not 100% familiar with the code (for reasons explained in a Discussion), meaning that I will need to do some learning to help people better.
I am quite busy right now, as my library is coming up to release. But hopefully after that I can spend a lot more of my time on here helping users.
I have been thinking for a while that flutter_map may need rewriting to a certain extent, but that conversation is out of scope for this issue.

In the meantime, it might help if you can:
 - Give information about the device that this library is crashing on
 - Try progressively manually going back through commits (using dependencies from Git), to see where this issue was introduced
 - Attach any screen recordings

Thanks for your report, and sorry I'm unable to assist very well at the moment!

**Comment by ibrierley** [comment]
I think for this one to get resolved, we need a minimal example to reproduce the problem look at.

**Comment by comatory** [comment]
I'm running into same issue. Happens on Android but it's hard to reproduce, it only happens sometimes. I get no stack trace, the crash doesn't even trigger telemetry (Sentry) so it's hard to tell what's going wrong.

**Comment by ibrierley** [comment]
It this using a wms layer ? What else is going on (displayed) out of interest ?

**Comment by comatory** [comment]
> It this using a wms layer ? What else is going on (displayed) out of interest ?

Actually I'm sorry. I replied to wrong issue. My problem is most likely this: https://github.com/fleaflet/flutter_map/issues/1154

Again, apologies.

**Comment by ibrierley** [comment]
Note, if its the polyline issue, you could try the saveLayer hack mentioned there, see if it helps. If it does, I think its one that may make us more likely to ditch remove it from the code or have it as an option or something.

**Comment by comatory** [comment]
Yeah. I'm having hard time reproducing it, it seems random but there has
to be something that occurs.

I'll try removing polylines completely once I figure out how to reproduce
it in my app. That should rule it out.

**Comment by comatory** [comment]
On Mon May 23, 2022 at 8:48 PM CEST, Luka S wrote:
> @comatory Do you have any news on this? Would be great to hear!

Unfortunately I did not have time to reproduce the issue.
