### ISSUE TITLE
[FEATURE] User Location

### ISSUE THREAD

**Issue by CyberDepot** [fleaflet/flutter_map#1196]
Hi

you have 3 plugin for show user location
**user_location_plugin** And **flutter_map_location** is discontinued
**flutter_map_location_marker** is not working (i test it many times and run example and its not working, i build example on my phone and emulator but not working)

flutter_map give user location but i need a plugin like this for show accuarcy and course 
are you have a plan for this feature?
are you have same plugin for replace with those?

**Comment by JaffaKetchup** [comment]
Unfortunately, this is out-of-scope for 'flutter_map' at the moment. You should implement this yourself, or use a plugin.

If you're interested, here is a newer list of supported plugins: https://flutter-map.vercel.app/plugins/list. 'flutter_map_location_marker' has worked in the past for me, but I haven't used it recently, so things may have changed.

If 'flutter_map_location_marker' still doesn't work, try ensuring you have granted the correct permissions to your app, and installed the plugin correctly, otherwise consider raising an issue there.

Many thanks for using 'flutter_map', and please feel free to raise more issues should you need to :)
