### ISSUE TITLE
TileMill lost support

### ISSUE THREAD

**Issue by AlysonTrizotto** [fleaflet/flutter_map#1204]
Does anyone have an idea of ​​a tool to assemble a map other than TileMill? That has MBTiles export? Because tilemill lost support, it's not working... It was replaced by Mapbox Studio.

**Comment by ibrierley** [comment]
Isn't tilemilll open source (even if mapbox has kinda taken over)...i.e    https://tilemill-project.github.io/tilemill/ ? Or are there some things now that need sorting that no one will do  ? (never been very familiar with tilemill)

**Comment by emallay** [comment]
I build apps for long-distance hikers where offline maps are critical. I've used the free Maperitive tool for many years, with good results. It's Windows-only, which for me is a pain since I'm on a Mac, but it runs fine through a VM.

It's very quirky and doesn't handle very large maps particularly well (because everything is processed in memory), so I need to split up tile generation by regions. But the map theme is highly customizable, contour lines and hill shading can easily be added, and there's a lot you can do with it. 

There's a non-trivial learning curve, though, and not a lot of learning resources, so be prepared for a lot of trial-and-error and more than a little cursing-and-screaming at your computer (alas!). I use various python tools (some public, some in-house) to prepare the map data, set up polygons for the coverage area, and so on, and then run Maperitive overnight via a VM that just churns out tiles. 

FYI, MBTiles is just a database format. So long as you can create the tiles in an appropriate directory structure you can use 3rd party utilities (like the 'mbutil' python package) to assemble them into an MBTiles database. 

Good luck with it!

**Comment by JaffaKetchup** [comment]
Here's the full list from the official OSM wiki: <https://wiki.openstreetmap.org/wiki/Rendering>

---

Can confirm Maperitive seems a good option for beginners, but I couldn't render Great Britain's extract to the PREVIEW on my machine: it's very memory intensive.
If you want to run your own server, lookup Switch2OSM's guides; this also needs a good machine, but I got it running slowly on a Linux VM on my Windows host.

---

Other than that, I'm going to have to close this issue as it's a bit open-ended and a bit out of scope. If you still need more help, consider [joining the Discord server](https://discord.gg/egEGeByf4q), or create a Discussion. Thanks!
