### ISSUE TITLE
[BUG] Gesture pinch zoom: wrong centre focal point

### ISSUE THREAD

**Issue by LondonJammo** [fleaflet/flutter_map#1227]
The pinch to zoom Gesture always zooms in and out of the map focused on the centre of the map, not the centre of the gesture. For example, if I want to zoom into the bottom left corner, I currently cannot do that.

When you start the gesture and move your fingers around, the centre point also moves, however the initial zoom focal point is not where expected. Is this a setting/flag that I have missed and need to set, or a known bug?

Thanks

**Comment by ibrierley** [comment]
It should be fixed, if you use the version from Git.

**Comment by LondonJammo** [comment]
> It should be fixed, if you use the version from Git.

I'm using 0.14.0 - which is latest here and pub.dev flutter_map . Was it a recent bug fix?

**Comment by ibrierley** [comment]
I'm fairly sure It was after 0.14.0 iirc, and almost certainly if that pinch/zoom off center doesn't work. There's been a few fixes/improvements which are in Git, but not released to pub.dev yet (something that's under discussion/review atm), so I would recommend trying it and see if it fixes your problem. Otherwise wait until next release, but not sure when exactly that will be just yet.

**Comment by JaffaKetchup** [comment]
Closing this as I'm pretty sure this is fixed in a Git version.
To get this functionality, depend on this package as seen in the [new docs installation instructions](https://fleaflet-docs.netlify.app/introduction/go#from-githubcom). If you need to use other packages that depend on 'flutter_map' from 'pub.dev', use a `dependency_overrides` section instead.

**Comment by LondonJammo** [comment]
I've still got the same centre-screen-zoom-only problem with the latest versions at: 
`flutter_map: ^0.14.0`
and 
`flutter_map: git: url: https://github.com/fleaflet/flutter_map.git`

**Comment by ibrierley** [comment]
If you do
```
 flutter pub deps | grep flutter_map
```
What does it report ?
