### ISSUE TITLE
[FEATURE] Routing support

### ISSUE THREAD

**Issue by AbbasHoseini** [fleaflet/flutter_map#1249]
Hey.
First thanks for this good package.
I want to draw a road in open street map but I couldnt find any way in this package.

**Comment by ibrierley** [comment]
You will need to be a bit more precise. What type of road, from where is the source of the road ? There are things like polylines you may be able to use, or there's a vector tile plugin etc, but you need to include more information.

**Comment by AbbasHoseini** [comment]
thanks for reply, 

> You will need to be a bit more precise. What type of road, from where is the source of the road ? There are things like polylines you may be able to use, or there's a vector tile plugin etc, but you need to include more information.

thanks for reply, For example I give two points and map finds a road between these points. 
look at this image:
[https://miro.medium.com/max/742/1*Cz7pyr_jn21MreFNysY6Vg.png](url)

**Comment by ibrierley** [comment]
ah ok, you mean a navigation route. I guess it may depend on the source still...example https://github.com/JaffaKetchup/flutter_osrm may help, but normally its not too tricky to feed a result of latlongs returned from some other source into a polyline. So again, it depends where the source is from...otherwise if you haven't got that far, you could look into things like Mapbox directions api. It may depend if you are fine with paying for that, often there are free services for limited use at first.

**Comment by JaffaKetchup** [comment]
Yeah, was just about to say that this library doesn't support routing, as it's out of scope. My plugin linked above is still in alpha, so is not for production use. I'd recommend using OSRM directly (free but limitations unless you serve your own backend), or Mapbox (paid), and just putting the results into a `Polyline`.

**Comment by AbbasHoseini** [comment]
@ibrierley @JaffaKetchup Thanks to you
