### ISSUE TITLE
[BUG] Map rotation not always between 0° & 360°

### ISSUE THREAD

**Issue by mapfu** [fleaflet/flutter_map#1282]
When I rotate any map with my fingers, the reported map controller rotation can go beyond 360 deg or - 360 deg. For example, if I rotate the map a full 2 rotations from 0, rotation will return 720. Or -720 if I rotate the the other way. 

I expected the rotation value to be just 0 - 359. Is this a bug? I doubt it, but I don't understand why it is this way. I want to do a nice smooth animated rotation reset for the map, so I'll just do the math. Thanks for a great mapping tool.

**Comment by JaffaKetchup** [comment]
Hi there @mapfu, and sorry for the long wait.
I don't think that this is intended functionality. However, it should be theoretically easy to divide the number by 360 to get the number of rotations, with the remainder being the exact angle between 0 and 360. Therefore, I don't think we're going to fix this.
Thanks for your interest, and we're happy to answer more questions in the future!

**Comment by ibrierley** [comment]
Yeah, not really sure if it's intentional or not, but it may make sense. Let's say you want to animate from 358 to 362 (or 2), but you want it to only go clockwise...it's pretty intuitive just to just increase the angle. If we modded it by 360, if our gesture went from 358 degrees to 2, did it go clockwise or anticlockwise ?

Probably some flaws in that, but just guessing.

**Comment by mapfu** [comment]
Ok thanks
