### ISSUE TITLE
[BUG] Crossing W/E Extremity With `Polyline` Results In Unexpected Lines

### ISSUE THREAD

**Issue by WorldpixelSoftware** [fleaflet/flutter_map#1338]
### What is the bug?

I was trying to implement a great circle map between two points using the OSM Map.

All is good as long as you don't cross 180E/W. Then the line suddenly jumps to the other side of the map.

![flutter_map_bug](https://user-images.githubusercontent.com/77431217/184257980-c3f2403b-5b70-4dc5-861b-83928b593485.png)

### What is the expected behaviour?

Having a closed line between the two points. On low zoom levels (like OSM 0), there should be just two renders of any layer at a given coordinate.

### Do you have a potential solution?

Maybe mirroring the coordinates is possible somehow? So that a marker or a line is shown twice on low zoom levels.

### Platforms Affected

Android, iOS, Windows, MacOS

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there, and thanks for the report! 
We've known about this issue for a while, but have never tried to resolve it as it seems to be a rare-ish occurrence. Can you try splitting your line into two parts, where one starts/ends at 180 and the other at -180?

**Comment by KKStudios** [comment]
@JaffaKetchup Yeah splitting the lines was basically my workaround for this situation. I just think that looks weird though.

What would be really great is to have a map view, that has no physical boundaries left and right, basically like when you go on google maps and pan from one side to the other and the map just "rotates" in view

I've included two pictures of what I would consider expected behaviour for a map projection.

But thank you for your time and effort that went into this project!

![maps_ew_crossing](https://user-images.githubusercontent.com/77431217/185460713-d1e11bef-fce5-41da-9822-f744826d6781.png)
![gcmapper_ew_crossing](https://user-images.githubusercontent.com/77431217/185460737-0fdac27d-cba1-421e-8f4a-76283facfbe8.png)
.

**Comment by JaffaKetchup** [comment]
Hi there @KKStudios, and sorry for the delay.
I think someone else wanted infinitely panning maps, but that's quite a low priority. Can you send some pictures of how the splitting technique looks?

**Comment by zery6** [comment]
> @JaffaKetchup Yeah splitting the lines was basically my workaround for this situation. I just think that looks weird though.
> 
> What would be really great is to have a map view, that has no physical boundaries left and right, basically like when you go on google maps and pan from one side to the other and the map just "rotates" in view
> 
> I've included two pictures of what I would consider expected behaviour for a map projection.
> 
> But thank you for your time and effort that went into this project!
> 
> ![maps_ew_crossing](https://user-images.githubusercontent.com/77431217/185460713-d1e11bef-fce5-41da-9822-f744826d6781.png) ![gcmapper_ew_crossing](https://user-images.githubusercontent.com/77431217/185460737-0fdac27d-cba1-421e-8f4a-76283facfbe8.png) .

Hi there @KKStudios,  
I have the same problem, 
Can you show your solution code? 
Thx!

**Comment by KKStudios** [comment]
@JaffaKetchup 

Here is how a workaround would look like splitting the path into two..

If you ask me, looks pretty crappy, that's why I won't implement that right now.

![180_crossing](https://user-images.githubusercontent.com/77431217/192373962-b46c50d1-f782-46bb-bb72-0be0e43591b2.png)

But probably would make a lot of work for the project to change to some kind of infinite scrolling map.

Cheers

**Comment by JaffaKetchup** [comment]
@KKStudios 
Yeah, I can see that's less than desirable. There has been some talk on reworking the tile layer mechanics, and infinite functionality may be a part of this; but for now, it's unlikely we'll implement it.
(Anyone else reading and wants to submit a PR, please do!)

Thanks for your insight :)

**Comment by KKStudios** [comment]
@zery6 
Would be to much code to post right now since it's all integrated in my project and using internal utilities...
But basically you just calculate where the great circle between two points crosse 180E/W.

Then you do polylines between that point and your departure/ destination point. Thats it.

Formula for calc can be found here: https://edwilliams.org/avform147.htm
Very neat comprehension.

**Comment by KKStudios** [comment]
@JaffaKetchup 
Ok no problem. Maybe I'll have a look into it if modifying the project and digging into the codebase is worth the effort or implementing a scrolling map from scratch with only the required functionality is less work.

Just not my no1 priority right now.

Thanks anyhow.

**Comment by ibrierley** [comment]
If you felt brave, and wanted to have a play with a very alpha plugin, my vector slicer plugin can draw across lines across the dateline, and also repeat (but not infinite). Examples of the effect would be https://fluttermap.dabbles.info/dateline_test/#/ https://fluttermap.dabbles.info/geoslicer/#/ you should see the repeats if you zoom out (dateline crossing in first example, repeated none dateline stuff with simple clustering in 2nd). 

Repo at https://github.com/ibrierley/geojson_vector_slicer Basically it's a fast way with functionality to draw geometry.

Couple of thoughts worth bearing in mind. It's designed for more static geometry (i.e it may take a few seconds if its very complicated, like the US example). But it may be ok redoing relatively simple geometry more often, I've not really tested that. Erm and it's very much a pre alpha :). But if someone else ever wanted a play, I'd probably work on it.

It's designed for geojson, but one could convert to geojson relatively quickly, I could probably add a method to do that.

**Comment by ivanzhadnov** [comment]
Hi 
could you please inform is it bug will be solved at next release?

**Comment by ibrierley** [comment]
It's currently unlikely (unless someone wants to submit a PR).

**Comment by monsieurtanuki** [comment]
I solved a similar issue in https://github.com/osmdroid/osmdroid, years ago.

If I remember well the idea is:
* to know the width of the world, in pixels
* to check each time we add a projected point - if I added/subtracted the world width, would I be closer to the previous polyline point?
* probably use the polyline center in order to decide which part of the world to center the polyline on
* possibly display as many identical polylines as the world replications need

**Comment by monsieurtanuki** [comment]
@JaffaKetchup I'm currently working on it. There are similarities with the "teleporting marker" issue.

**Comment by WorldpixelSoftware** [comment]
https://github.com/user-attachments/assets/f6d9bf9f-9224-4ce2-bbf4-45b6f1789b69

@JaffaKetchup 
Well thank you for fixing this but somehow the polylines disappear when moving or zooming.

I just did a short Testsetup with the following coordinates:

```dart
              PolylineLayer(
                  polylines: [
                    Polyline(
                        color: Colors.red,
                        strokeWidth: 4,
                        points: [LatLng(22.30035, 113.92591), LatLng(50, 179), LatLng(39.04872, -84.66257)]
                    ),
                  ]
              )
```

I saw in your PR logs that something like this happened before but was marked as closed and fixed.
Upgraded to flutter_map: ^8.1.1 before testing.

**Comment by monsieurtanuki** [comment]
@WorldpixelSoftware I've managed to reproduce your issue with #2069.
The problem seems to be with culling.
Would you please try with `cullingMargin: null`?

**Comment by WorldpixelSoftware** [comment]
@monsieurtanuki Good point. Solved it but I guess it's still kind of unintended behaviour? At least UX wise.
Thank you!

**Comment by monsieurtanuki** [comment]
@WorldpixelSoftware Needs to be fixed, indeed.
