### ISSUE TITLE
Add onSecondaryTap  (right-click for windows) callback 

### ISSUE THREAD

**Issue by Richard-Walter** [fleaflet/flutter_map#1444]
### What do you want implemented?

Please add the onSecondaryTap click callback so windows users can capture a right-click event when clicking on the map. 

### What other alternatives are available?

Currently, having to use the onLongPresss callback but this is not intuitive too windows users:

        onLongPress: (tapPosition, point) {

            showDialog(
                context: context,
                builder: (BuildContext context) {
                  return MapContextMenuDialog(tapPosition: LatLng(point.latitude, point.longitude));
                });
          },

### Can you provide any other information?

See https://api.flutter.dev/flutter/widgets/GestureDetector/onSecondaryTap.html

Heres a package that is capturing a right-click event to display a context menu:  https://pub.dev/packages/native_context_menu.

### Platforms Affected

Windows, MacOS, Linux

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by TesteurManiak** [comment]
Hi @Richard-Walter, I've investigated a bit on how to implement this feature, unfortunately it's not as easy as it seems because of a dependency to the package [positioned_tap_detector_2](https://pub.dev/packages/positioned_tap_detector_2) which hasn't been updated to support the `onSecondaryTap` event.

If we want to implement this feature we'll have to re-implement the `PositionedTapDetector2` widget by ourselves, which might not be a bad thing as we would rely on one less dependency but implies a bit of work.

**Comment by Richard-Walter** [comment]
Thanks for getting back to me.  I think it would be a useful feature to
have.  Hope you can get it to work :)
