### ISSUE TITLE
[BUG] Polyline with border ignores color in V4

### ISSUE THREAD

**Issue by Wackymax** [fleaflet/flutter_map#1510]
### What is the bug?

When setting a border color on a polyline the color property gets ignored and the polyline is drawn with a black color.

### How can we reproduce it?

Set the color property and the border color property on a polyline.

### Do you have a potential solution?

I may be wrong but it looks like the wrong color value is set in filterPaint in the polyline_layer class.

### Platforms

All flutter platforms

### Severity

Minimum: Allows normal functioning

**Comment by ibrierley** [comment]
I haven't got a lot of time to dig into it just atm, but I suspect it may be related to batching code, eg around https://github.com/fleaflet/flutter_map/commit/c4b66806a182e0d079dfea6f1a16d0fe83201e5b and if I revert to a previous commit to that it all works.

Maybe it's trying to batch forgetting about the separate layers when having a border or something.

**Comment by ibrierley** [comment]
I think the main problem is possibly the ordering of the paints is wrong. We want to draw the main path/paint after the borders, so I think that may be an easy fix if it comes to it..There's something a little different with the filterPaint/path I'm confused about, but I'm not entirely sure how that works...

Maybe we need to clarify the logic and reasons...we have 
1) the main paint/path, fine
2) if the borderStrokeWidth > 0 we set the borderPaint color...makes sense.
3) if the borderColor is not null, we set the filter paint and use Blendmode.dstOut 
( dstOut is == Show the destination image, but only where the two images do not overlap. The source image is not rendered, it is treated merely as a mask. The color channels of the source are ignored, only the opacity has an effect.)

Whats 3 for, is it for opacity on lines that have a border color or something ?

If someone needs a super quick fix, you could try swapping the order of the paints in polylinelayer.dart, but it would be nice before we do a change to know that its either a) the same as previous, or b) its different because of a fix (so need to double check lines with opacity and things like that).
