### ISSUE TITLE
[BUG] Web: Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by d1ss0nanz** [fleaflet/flutter_map#1654]
### What is the bug?

There seems to be a regression in v5 that is trying to set the `User-Agent` header on web.

### How can we reproduce it?

Use flutter_map in web application.

### Platforms

Flutter Web on Chrome

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hey @d1ss0nanz,
We're aware of this, and did this intentionally in order to simplify the code base. This shouldn't cause any issues.

**Comment by d1ss0nanz** [comment]
I've worked around this behaviour by implementing a custom `TileProvider` that removes the `User-Agent` header in `getImage`.

**Comment by ThomasAunvik** [comment]
@JaffaKetchup Why not just make the userAgentPackageName nullable? So then we can just set it to actually empty instead of 'unknown'.

https://github.com/fleaflet/flutter_map/blob/9211d54b32079ae31ec0c09fe828f2dcd5f434da/lib/src/layer/tile_layer/tile_layer.dart#L277
https://github.com/fleaflet/flutter_map/blob/9211d54b32079ae31ec0c09fe828f2dcd5f434da/lib/src/layer/tile_layer/tile_layer.dart#L299-L301

It spams the console log.
![image](https://github.com/fleaflet/flutter_map/assets/9968151/f1e2d416-0675-432e-8827-2b30cc6e5bd1)

**Comment by JaffaKetchup** [comment]
I guess if this is really bothering people, it may be possible just to check `kIsWeb`. I'll make a PR at some point.
