### ISSUE TITLE
[BUG] v6: Unable to smoothly rotate when colliding with constraints

### ISSUE THREAD

**Issue by tlserver** [fleaflet/flutter_map#1682]
### What is the bug?

User cannot zoomout or rotate by gesture if the space is not fully filled with tile.

### How can we reproduce it?

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class MinimumExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Minimum Example'),
      ),
      body: FlutterMap(
        options: const MapOptions(
          initialCenter: LatLng(0, 0),
          initialZoom: 1,
          minZoom: 0,
          maxZoom: 19,
        ),
        children: [
          TileLayer(
            urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
            userAgentPackageName:
                'net.tlserver6y.flutter_map_location_marker.example',
            maxZoom: 19,
          ),
        ],
      ),
    );
  }
}
```
0) This code set initialZoom to 1.
1) Try to move / rotate / zoom-out by gesture, and it is not work. (Note that minZoom = 0) Only zoom-in is working in this state.
2) Zoom in to zoom ~= 2 by gesture, and you will find that you cannot zoom it out back to zoom = 1 by gesture. (Stop at zoom ~= 1.5, which is according to your device's size)
3) Zoom in a little bit (around +0.2). Try to rotate the map now, and you will find that you have a very limited angle to rotate.

### Platforms

Android 13 [XiaoMi13i, MIUI Global 14.0.5]

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hi @tlserver, thanks for reporting.

Can you try disabling the new transparent gestures feature in MapOptions?

**Comment by tlserver** [comment]
Do you mean `applyPointerTranslucencyToLayers` option? Same behaviour if set it to false.

**Comment by tlserver** [comment]
In previous version, user can zoom in or out or rotate freely when zoom = 1 but keep seeing the gray background. I think this should be the default behaviour. Since seeing background is not a big problem to the user, but non- responding gesture is.

**Comment by JaffaKetchup** [comment]
You're right, the easy fix is to change this default.

However, I'm not so sure. Whilst we don't support infinite repeating Earth's, it's not great UX to let the users see these 'false' projections (as they won't be able to interact with them, because the lat/lng range is constrained to reality), let alone grey tiles.

The proper fix is to allow a rotation gesture to change the zoom level as necessary in order to comply with the constraints, then smoothly restore to the correct level as possible. But this does sound like a lot of work in an already overcomplicated system, so maybe we'll revert the change that changed this default 😂.
