### ISSUE TITLE
[BUG] `NetworkTileProvider` has poorer performance and new unhandled exceptions since v6

### ISSUE THREAD

**Issue by vitalsh** [fleaflet/flutter_map#1698]
### What is the bug?

Sometimes not all the tiles are being loaded/drawn.
After moving/dragging the map all the tiles are immediately drawn/refreshed

### How can we reproduce it?

It might be me with all the code in my project, but try with these tiles:
TileLayer(
        urlTemplate: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c', 'd'],
        tileProvider: NetworkTileProvider(),
        keepBuffer: 10,
        maxZoom: 23,
        retinaMode: false);

### Do you have a potential solution?

A workaround: add a method in MapController to refresh/redraw the tiles on demand.

### Platforms

All

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by vitalsh** [comment]
![flutter_map_tiles_not_loading](https://github.com/fleaflet/flutter_map/assets/20711095/e6db1a5d-3f94-4253-a59a-468f6ccf8b67)

**Comment by JaffaKetchup** [comment]
Can I ask what version you are running?

**Comment by vitalsh** [comment]
flutter_map: ^6.0.0

**Comment by JaffaKetchup** [comment]
Does the issue occur with the OSM tile server? (Note: only use the OSM tile server for testing.)

**Comment by vitalsh** [comment]
I don't use OSM (I use https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png). Can try and update.

**Comment by mattmyne** [comment]
I don't know if it's related but I'm running a local OSM server and having updated to flutter map v6 have noticed tiles take longer to display that with flatter map v5. Particularly when quickly zooming in and out, grey tiles are visible for a second or so in many places, when previously it would be almost instant (given local server). Nothing's changed on the server or it's caching.

**Comment by swust-xl** [comment]
I got the same problem.I upgraded flutter_map  from V4 to V6, then the console showed `ImageCodecException :Failed to detect image file format using the file header.
File header was [0x3c 0x21 0x44 0x4f 0x43 0x54 0x59 0x50 0x45 0x20].`
I found it was because the tile requested that didn't exist on Server or Assets.In V4 it throws a 404 NOT FOUND error,but in V6 it throws a ImageCodecException . I don't know in V6 why it always gave a strange fixed byte data when the tile request doesn't exist on server .To solve this problem just restrict CameraConstraint . But even the console shows no error log,  some tiles are still not shown correctly just like @vitalsh 's problem.

**Comment by manlyman29** [comment]
On a related note, the flutter map throws an exception each time it can not load a tile, and that makes debugging applications with a flutter_map widget, too troublesome. It constantly throws `Connection closed before header was received`, `Socket Exception`, and similar server-related errors and pauses the debug session. A fix or workaround for this would be great. This is happening in both OSM and MapBox tile servers.

**Comment by swust-xl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JaffaKetchup** [comment]
(@swust-xl Apologies, can you post that in English if you are able to?)

**Comment by JaffaKetchup** [comment]
@manlyman29 Are you also using the standard tile provider?

**Comment by JaffaKetchup** [comment]
@swust-xl That sounds possibly like a different problem.

**Comment by mattmyne** [comment]
> On a related note, the flutter map throws an exception each time it can not load a tile, and that makes debugging applications with a flutter_map widget, too troublesome. It constantly throws `Connection closed before header was received`, `Socket Exception`, and similar server-related errors and pauses the debug session. A fix or workaround for this would be great. This is happening in both OSM and MapBox tile servers.

To confirm I also get this if I just stop my local OSM server. Every time flutter map tries to load tiles (startup, move, zoom, etc.) I get something similar to this on the VS Code debug console:

`flutter:  (OS Error: The remote computer refused the network connection.

flutter: , errno = 1225), address = localhost, port = 64972, uri=http://localhost:8080/tile/18/130142/87058.png
flutter: ClientException with SocketException: The remote computer refused the network connection.`

At various times (I don't think every move, but most?) I also get:

`══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _ClientSocketException was thrown resolving an image codec:
ClientException with SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = localhost, port = 64838, uri=http://localhost:8080/tile/3/4/3.png

When the exception was thrown, this was the stack:
#0      IOClient.send (package:http/src/io_client.dart:119:7)
<asynchronous suspension>
#1      RetryClient.send (package:http/retry.dart:115:20)
<asynchronous suspension>
#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#3      BaseClient.readBytes (package:http/src/base_client.dart:58:22)
<asynchronous suspension>
#4      FlutterMapNetworkImageProvider._loadAsync (package:flutter_map/src/layer/tile_layer/tile_provider/network_image_provider.dart:84:11)
<asynchronous suspension>

URL: http://localhost:8080/tile/3/4/3.png
Fallback URL: null
Current provider: FlutterMapNetworkImageProvider()
════════════════════════════════════════════════════════════════════════════════════════════════════
`

...followed by lots of:

`Another exception was thrown: ClientException with SocketException: The remote computer refused the network connection.`

I don't recall the behaviour in version 5, but I don't remember having this stream of exceptions each time!

**Comment by JaffaKetchup** [comment]
I'm not sure why you didn't see these before, but that's normal! If you use a `NetworkImage` with an unreachable URL, it spits out a similar message as far as I can remember.

We MUST return an image or an error from inside an image provider. We could return a transparent tile instead of an error, but that would just hide the problem and potentially cause more issues. I guess the way to solve it now that we're using `logger` elsewhere is to create a custom error log, but then we're back to the same issue.

An unreachable URL or 404 response causing errors in console is OK. A 404 error attempting and failing to be decoded (invalid codec) as an image is not OK, and probably means we have a logic gap in our custom image provider - but I'll need to check that.

**Comment by mootw** [comment]
the custom image provider has historically thrown exceptions for network errors correct. in my app i use a custom tile provider that caches the tiles locally on disk. i need to re-write it soon with the new image decoder, but at the moment it also throws exceptions for network errors. , which can be annoying while debugging.

mine explicitly throws for all non-ok status codes. I believe my custom network provider is in the docs somewhere as the caching tiles example?
```dart
if (response.statusCode != HttpStatus.ok) {
        throw NetworkImageLoadException(
            statusCode: response.statusCode, uri: url);
      }
```

**Comment by manlyman29** [comment]
@JaffaKetchup Thanks for the reply, Yes it occurs on the standard NetworkTileProvider, with v6.0.0
I am not completely sure about earlier versions, I think this used to happen but a lot less.
Most of the time exception is from here:
![flutter_map](https://github.com/fleaflet/flutter_map/assets/63221039/cc65ac32-5f9d-4b3a-b55b-de5d696ceeb0)

**Comment by mattmyne** [comment]
I see what you're saying regarding the necessity of warning the user/program. I wonder if there's a way of reducing the frequency somehow though. Maybe after 10 tile exceptions in a row pause for a bit (and have a comment saying so?). It's just it seems while one exception/error is helpful, a massive stream of them is almost the opposite. I understand it's important to pick up cases where only one or two aren't loading, so a minimum threshold and pause might do both?

Maybe this isn't a priority as most people's URLs will be fine and they'll net connection, but thought I'd share my view given I'm getting notifications for this issue anyway 😉

**Comment by JaffaKetchup** [comment]
We could possibly return a custom image that just is red and has the text "Failure", but that seems like a lot of effort, and at that point, we should bring back the failure image argument. It also seems a bit OTT, but maybe that's the best option. Let me know what you think.

We could also add an argument to the provider to just ignore errors and return a transparent tile - and maybe combining this with the above might work.

(I know it's not always helpful, but I always use "Run Without Debugging" from VS Code. Contrary to the name, all of Flutter's DevTools are available, along with hot reload/restart, it just doesn't support breakpoints, and errors are just left in console.)

The reason it may be appearing more is because we reinforced our error catching in this region, as it was ignoring some errors before, which caused some issues. Possibly, it's because we're now `throw`ing every error caught inside the `catchError` block (which didn't exist before), rather than `rethrow`ing (because we can't inside `catchError`).

---

The comment https://github.com/fleaflet/flutter_map/issues/1698#issuecomment-1774564973 from above about a decoding error with 404 seems to be a different issue. With the changes to error handling in this area, we are now catching async errors directly from `decode`, rather than just using `try`/`catch`. Essentially, we're catching the error at decode time rather than response time, although I'm not entirely sure why this happens with some URLs and not others.

---

I've rewritten the `_loadAsync` method to be a little more flexible, reduce duplication, and stop mixing sync & async code:

```dart
 httpClient
    .readBytes(
      Uri.parse(useFallback ? fallbackUrl ?? '' : url),
      headers: headers,
    )
    .then((bytes) => ImmutableBuffer.fromUint8List(bytes))
    .then((buffer) => decode(buffer))
    .catchError((dynamic err) {
  // ignore: only_throw_errors
  if (useFallback || fallbackUrl == null) throw err as Object;
  return _loadAsync(key, chunkEvents, decode, useFallback: true);
});
```

I can't see a difference, but maybe there'll be a difference for some people.  
It's also worth noting that this is more customizable. Rather than using a catch-all `catchError`, we could use the `onError` callback inside each `then` to handle each error more specifically - but I can't really see the point in that for now.

Open to other suggestions to change the way this works.

**Comment by JaffaKetchup** [comment]
Of course, the ideal method would be to copy the implementation of `NetworkImage` closely, but that does involve a separate implementation for IO and web. I'll see if I can do it.

**Comment by mootw** [comment]
the readBytes function returns a ClientException if the status code is not success, so that would explain why the 404 status codes are getting thrown up

**Comment by JaffaKetchup** [comment]
Yeah, but I thought we had that in earlier version tbh.
Turns out, copying Flutter's network image implementation is quite difficult as they go quite deep into the behind-the-scenes implementations, particularly on the web.

**Comment by JaffaKetchup** [comment]
@mattmyne @manlyman29 @swust-xl Please use #1703 to discuss anything about error handling. This issue should solely be used for its original purpose about reporting a performance issue with the default image provider.

**Comment by robiness** [comment]
Commenting on @manlyman29 issue: https://github.com/fleaflet/flutter_map/issues/1698#issuecomment-1775917057

We also ran into this when migrating to V6.
Previously we had a static TileLayer, so only a single instant was used, leading into those Client already closed errors.
Making it a getter, or caching the HttpClient did solve the problem for us.

**Comment by TesteurManiak** [comment]
@LeeMatthewHiggins if you think your issue comes from flutter_map_animations I invite you to check this issue to see how you can add a `TileUpdateTransformer` https://github.com/TesteurManiak/flutter_map_animations/issues/13

**Comment by LeeMatthewHiggins** [comment]
> > @LeeMatthewHiggins if you think your issue comes from flutter_map_animations I invite you to check this issue to see how you can add a `TileUpdateTransformer` [TesteurManiak/flutter_map_animations#13 (comment)](https://github.com/TesteurManiak/flutter_map_animations/issues/13#issuecomment-1763357594)
> 
> I have tried this in combination with the cancellableNetworkTileProvider. both together seem worse. This on its own seems better, if you move the map after it has stopped, else tiles fail to display, but then pop in instantly if you move manually.
> 
> Today I investigated. It seems many tiles that are outside the animation path are being loaded. I start the map zoomed in and animate to a location after a request is completed to get the location (i also tried starting zoomed out).
> 
> <img alt="Screenshot 2023-11-01 at 15 27 38" width="1441" src="https://user-images.githubusercontent.com/496316/279707334-8147a2fd-5d28-4af1-99ed-0bb26cf5f060.png">

I switched to open street map tiles and intially looked good, but a few minutes of use and the same issues. I actually starting to think there might be some denial or service system kicking in, this would explain why sometimes it can work, but after some use it just grinds to a halt, seems to be the case if i switch from wifi to 3G too. 

With open street maps I get this a lot after 5 1 minute of use.
I get this a lot "flutter: ClientException: Connection closed before full header was received, uri=https://tile.openstreetmap.org/4/7/6.png"
With mapbox it was something similar.
Also just got my mapbox bill and it was 248k tile requests in one month (only with a hand full of test uses while in development)

**Comment by JaffaKetchup** [comment]
I wonder whether the changes made to `panBuffer` might be having an effect here. In V6, it defaults to 1 or 2 (I can't remember), but it defaulted to 0 in v5. I changed it to attempt to improve the UX by removing grey loading tiles, but I wonder whether it's loading more images at once, and so they're all a little bit slower.
What happens if you disable `TileLayer.panBuffer`?

**Comment by LeeMatthewHiggins** [comment]
> > > @LeeMatthewHiggins if you think your issue comes from flutter_map_animations I invite you to check this issue to see how you can add a `TileUpdateTransformer` [TesteurManiak/flutter_map_animations#13 (comment)](https://github.com/TesteurManiak/flutter_map_animations/issues/13#issuecomment-1763357594)
> > 
> > 
> > I have tried this in combination with the cancellableNetworkTileProvider. both together seem worse. This on its own seems better, if you move the map after it has stopped, else tiles fail to display, but then pop in instantly if you move manually.
> > Today I investigated. It seems many tiles that are outside the animation path are being loaded. I start the map zoomed in and animate to a location after a request is completed to get the location (i also tried starting zoomed out).
> > <img alt="Screenshot 2023-11-01 at 15 27 38" width="1441" src="https://user-images.githubusercontent.com/496316/279707334-8147a2fd-5d28-4af1-99ed-0bb26cf5f060.png">
> 
> I switched to open street map tiles and intially looked good, but a few minutes of use and the same issues. I actually starting to think there might be some denial or service system kicking in, this would explain why sometimes it can work, but after some use it just grinds to a halt, seems to be the case if i switch from wifi to 3G too.
> 
> With open street maps I get this a lot after 1 minute of use. I get this a lot "flutter: ClientException: Connection closed before full header was received, uri=https://tile.openstreetmap.org/4/7/6.png" With mapbox it was something similar. Also just got my mapbox bill and it was 248k tile requests in one month (only with a hand full of test uses while in development)

OK the AnimatedMapController is the main issue for me... I just switched to the standard controller and although now my transitions are ugly its working as I would expect. Its seems that the animation controller (plus any other flutter animation) is triggering a crazy amount of tile requests, even the methods to mitigate this seem to not be able to cope (the cancellable provider and the tile update transformer), . IMO the camera animation needs to be tightly integrated to the core map system.

**Comment by LeeMatthewHiggins** [comment]
Yes I´m using the transformer as @TesteurManiak suggested. If I combine that with the cancel tile provider I get situations that never load the tiles unless I then manually move the map If I use it on its own it may improve, but on 3G connection its still not usable. If i remove all the "hacks" and don't use the animated controller then its usableble. If I use google maps tiles then its very performant.

My conclusion is the tile provider makes a big difference, and if I remove the animation then its usable. I suspect that some kind of rate limit is happening due to the large amount of requests, as it seems to work from cold and after a minute grind to a halt (when using the animation). Feels like there is a fundimental issue that the animation acts as a stress test for. As a test you can animate between points (at least 100km apart) and use the network link conditioner or a slow connection.

You can see I have tried many combinations....

<img width="628" alt="Screenshot 2023-11-02 at 10 19 05" src="https://github.com/fleaflet/flutter_map/assets/496316/92afb74a-cbd4-43b9-ab24-0d1fe5f9d2e5">

**Comment by TesteurManiak** [comment]
@LeeMatthewHiggins Have you also correctly set the `customId` property as mentioned on the issue? https://github.com/TesteurManiak/flutter_map_animations/issues/13#issuecomment-1763811143

**Comment by LeeMatthewHiggins** [comment]
I just removed the check to turn it on and off so its always on. I see the print statements Loading tiles etc.
<img width="549" alt="Screenshot 2023-11-02 at 10 45 53" src="https://github.com/fleaflet/flutter_map/assets/496316/f0ee41bc-f2df-41e1-bc78-f89b25a7925e">

**Comment by TesteurManiak** [comment]
@LeeMatthewHiggins this is not what I was asking, have you specified the `customId` property to the "animated" method you are calling. Here's the example mentioned in the comment of the issue:
```dart
static const _useTransformerId = 'useTransformerId';

 GestureDetector(
  onTap: () => _animatedMapController.animateTo(
    dest: point,
    customId: _useTransformer ? _useTransformerId : null, // Here
  ),
  // ...
)
```

**Comment by TesteurManiak** [comment]
Yes the custom id **is needed** to use the transformer otherwise the transformer won't be able to identify a movement animation to fetch only the destination's tiles.

**Comment by LeeMatthewHiggins** [comment]
OK I have tried this out again, as I really want nice animations. I added the customId. However I do get tiles not loading. Its like the end frame that clips the tiles is not correct, you can see in this video that the tiles are loaded, you just have to move the map to have them pop in. The Tile update transformer does solve the massive amount of requests, but has this other issue that i actually think is just clipping the tiles rather than no loading, as they seem to instantly appear if you move the map manually. heres what I get...

[Video](https://drive.google.com/file/d/1Vr5xX4Gb1Tx7my8enh2u51vf12IPIZ2S/view?usp=drive_link)

**Comment by LeeMatthewHiggins** [comment]
Small update, I have refactored my app to make it as simple as possible, removed all flutter animations that would resize the flutter map widget or make it rebuild. I fix the map size so there is no movement. Seemed to work great. however I got this (see link video). Which now is exactly the same issue as the orginal issue reporter had. It doesn´t happen all the time, but when it does the same tiles never load in that session. if you move the map then others load. So i think there is maybe an issue with the way the system handles errors (maybe caching the error).

[https://drive.google.com/file/d/1K_59jxAUoblsdwdVSzImhdbUf7mgPVOb/view?usp=sharing](url)

**Comment by MendleM** [comment]
This is a major blocker for our next app release. Anything I can do to help? Would love to see this issue resolved. Tiles don't load on the initial load sometimes. I notice this happens at specific zoom levels from initial load. So if I zoom in slightly it will show tiles but as soon as I zoom back out to the zoom level of the initial load, those initial failed to load tiles are still missing.

**Comment by MendleM** [comment]
I've implemented a retry mechanism into the `CancellableNetworkTileProvider` which seems to fix it for now:

```dart
import 'dart:async';
import 'dart:ui';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_map/flutter_map.dart';

class CancellableNetworkTileProvider extends TileProvider {
  CancellableNetworkTileProvider({super.headers}) : _dio = Dio();

  final Dio _dio;

  @override
  bool get supportsCancelLoading => true;

  @override
  ImageProvider getImageWithCancelLoadingSupport(
    TileCoordinates coordinates,
    TileLayer options,
    Future<void> cancelLoading,
  ) =>
      _CNTPImageProvider(
        url: getTileUrl(coordinates, options),
        fallbackUrl: getTileFallbackUrl(coordinates, options),
        tileProvider: this,
        cancelLoading: cancelLoading,
        maxRetryCount: 3, // Set the maximum number of retries
      );

  @override
  void dispose() {
    _dio.close();
    super.dispose();
  }
}

class _CNTPImageProvider extends ImageProvider<_CNTPImageProvider> {
  final String url;
  final String? fallbackUrl;
  final CancellableNetworkTileProvider tileProvider;
  final Future<void> cancelLoading;
  final int maxRetryCount;

  const _CNTPImageProvider({
    required this.url,
    required this.fallbackUrl,
    required this.tileProvider,
    required this.cancelLoading,
    required this.maxRetryCount,
  });

  @override
  ImageStreamCompleter loadImage(
    _CNTPImageProvider key,
    ImageDecoderCallback decode,
  ) {
    final chunkEvents = StreamController<ImageChunkEvent>();

    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key, chunkEvents, decode, maxRetryCount),
      chunkEvents: chunkEvents.stream,
      scale: 1,
      debugLabel: url,
      informationCollector: () => [
        DiagnosticsProperty('URL', url),
        DiagnosticsProperty('Fallback URL', fallbackUrl),
        DiagnosticsProperty('Current provider', key),
      ],
    );
  }

  @override
  Future<_CNTPImageProvider> obtainKey(
    ImageConfiguration configuration,
  ) =>
      SynchronousFuture<_CNTPImageProvider>(this);

  Future<Codec> _loadAsync(
    _CNTPImageProvider key,
    StreamController<ImageChunkEvent> chunkEvents,
    ImageDecoderCallback decode,
    int remainingRetries, {
    bool useFallback = false,
  }) async {
    final cancelToken = CancelToken();
    unawaited(cancelLoading.then((_) => cancelToken.cancel()));

    try {
      final response = await tileProvider._dio.get<Uint8List>(
        useFallback ? fallbackUrl! : url,
        cancelToken: cancelToken,
        options: Options(
          headers: tileProvider.headers,
          responseType: ResponseType.bytes,
        ),
      );

      return decode(await ImmutableBuffer.fromUint8List(response.data!));
    } on DioException catch (e) {
      if (CancelToken.isCancel(e)) {
        return decode(
          await ImmutableBuffer.fromUint8List(TileProvider.transparentImage),
        );
      }
      if (remainingRetries > 0 && !useFallback) {
        // Retry the request
        return _loadAsync(key, chunkEvents, decode, remainingRetries - 1);
      } else if (fallbackUrl != null && !useFallback) {
        // Try loading from the fallback URL
        return _loadAsync(key, chunkEvents, decode, maxRetryCount, useFallback: true);
      }
      rethrow;
    } catch (_) {
      if (remainingRetries > 0 && !useFallback) {
        // Retry the request
        return _loadAsync(key, chunkEvents, decode, remainingRetries - 1);
      } else if (fallbackUrl != null && !useFallback) {
        // Try loading from the fallback URL
        return _loadAsync(key, chunkEvents, decode, maxRetryCount, useFallback: true);
      }
      rethrow;
    }
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is _CNTPImageProvider && url == other.url && fallbackUrl == other.fallbackUrl);

  @override
  int get hashCode => Object.hashAll([url, fallbackUrl]);
}
```

**Comment by JaffaKetchup** [comment]
Related (also to #1703):
- flutter/flutter#132912
- flutter/flutter#129121
- flutter/devtools#5883

I'm not 100% sure why this happens - but I'm not sure there's so much we can do in regards to sometimes failing to fetch tiles. HTTP IO is a bit of a mess in Flutter/Dart.

Just check that this All Exceptions box is disabled for starters:
![image](https://github.com/fleaflet/flutter_map/assets/58115698/d98fa7d5-9086-492c-a25c-6dcaca9c47a2)

For example, with it enabled, I get this strange error - but the tiles still load perfectly fine afterward:
![image](https://github.com/fleaflet/flutter_map/assets/58115698/d656b800-16a8-445d-a4d9-8de26bd8c0f1)

---

In terms of performance, I'll see what I can do, but I'm not confident there is so much. I will simplify as I mentioned in https://github.com/fleaflet/flutter_map/issues/1698#issuecomment-1775968008, hopefully that will help a bit.

**Comment by JaffaKetchup** [comment]
In terms of the issues with early HTTP client cancellation, that will be caused when the `TileProvider` providing the tiles is destroyed (when the `TileLayer` is destroyed) but still trying to load tiles. We'll see whether we can do anything about this.

**Comment by JaffaKetchup** [comment]
#1742 should hopefully fix this. We're now following much closer to what Flutter documents for implementers of an `ImageProvider` - although there are still some differences.
For those using `CancellableNetworkTileProvider`, follow fleaflet/flutter_map_cancellable_tile_provider#4 & expect it in v2.

(It definitely fixes the "ClientException: Connection closed while receiving data" and "ClientException: Client already closed" issues.)

**Comment by saropa** [comment]
Hi all, just adding a note that this PR 1742 (https://github.com/fleaflet/flutter_map/pull/1742) did fix our  "connection attempt cancelled" (grey tiles) issues.

**Comment by swust-xl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
