### ISSUE TITLE
[FEATURE] Load tile layer from geopackage raster tile

### ISSUE THREAD

**Issue by kttary** [fleaflet/flutter_map#1737]
### What do you want implemented?

Is there a plan to support geopackage raster tile as overlay or base tile layer? With geopackage raster tile support we can create offline app and this kind of app very helpful on dissaster area, rain forest etc

### Severity

Minimum: Not required for my use

**Comment by josxha** [comment]
> Is there a plan to support geopackage raster tile as overlay or base tile layer?

There probably won't be a support for geopackage files by `flutter_map` directly because of its needed sqlite dependency. There is however a package called [flutter_geopackage](https://pub.dev/packages/flutter_geopackage) that supports reading geopackage files. You extend from the `TileProvider` class to create your own TileProvider and use it inside.

**Comment by josxha** [comment]
@kttary do you need to have support for tiles only or want to store geometry objects as well? I'm am currently working on a mbtiles provider with the benefit that it supports pbf and webp tiles as well (however it doesn't support geometry objects).

**Comment by kttary** [comment]
i need both tile and geometry. i'am able to read the geopackage geometry to polygon/polyline/point but i have no idea to read and display the tiles. maybe you have some clues to start?

**Comment by josxha** [comment]
1. As mentioned extend extend from `TileProvider` to create your own tile provider.
2. Pass your GeopackageDb as a parameter to your tile provider.
3. Query the specific tiles inside of the tile provider.

See for example `FileTileProvider` as an example how the implementation is done.
