### ISSUE TITLE
[BUG] `MapOptions.applyPointerTranslucencyToLayers` causes `Positioned` wrappers to fail

### ISSUE THREAD

**Issue by Zverik** [fleaflet/flutter_map#1740]
### What is the bug?

I have been using `Positioned` extensively to place buttons around the map. This was validated by [some of the examples](https://github.com/fleaflet/flutter_map/blob/master/example/lib/widgets/drawer/floating_menu_button.dart). But those widgets [are required](https://api.flutter.dev/flutter/widgets/Positioned-class.html) to be placed in a Stack with no `RenderObjects` inbetween.

In 6.0.0 widgets, instead of being put in a Stack, [are all wrapped](https://github.com/fleaflet/flutter_map/commit/4ba3d02827dd0e3b6b20fc58b0b62d3f58160b54#diff-3d1ec1773715ac2564805c37018286dc1fee2c4087990e430611e27a7641d098L112) in `TranslucentPointer` objects. Which leads to positioning not working, and multiple error notices in a log.

Can this thing you wanted to do be done differently? Or, are there alternatives to positioning widgets inside the map?

I thought of putting those on top of the map instead, but in that case those widgets (e.g. zoom buttons) won't have access to map state.

### How can we reproduce it?

Use the `Positioned` widget as a top-level one for a map layer.

### Do you have a potential solution?

Make `applyPointerTranslucencyToLayers` flag not wrap widgets, instead of setting a property of `TranslucentPointer`?

Alternatively, a way to properly upgrade such plugins needs to be documented. `Align` widget doesn't work for bottom-aligned buttons, for example.

### Platforms

Android 12

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Thanks for reporting.

Yes, this is an issue I didn't foresee. I didn't expect that a `RenderObject` non-`Widget` would cause issues.

It's worthwhile saying that non-map related widgets shouldn't be put inside the FM stack, but I can see that if a widget needs to access the context/inherited aspects, then it makes sense.

We actually did realise that this implementation might be an issue a couple of weeks ago, due to the fact that this will result in being able to press a button located behind another.

The real solution is to build layers (and fix the existing ones) to not handle taps when unnecessary, or individually wrap with the provided `TranslucentPointer` themselves if necessary. I think the best temporary solution is as you suggested.

As a short term workaround, put the buttons in a stack outside FM, and use a map controller as you may have done previously. Let me know if there's an issue with that.

**Comment by Zverik** [comment]
So what I did was replacing `Positioned` with `Align` + `Padding`. That at first did not work for widgets with `Column`s inside them, but `mainAxisSize: MainAxisSize.min` fixed that.

**Comment by JosefWN** [comment]
> It's worthwhile saying that non-map related widgets shouldn't be put inside the FM stack, but I can see that if a widget needs to access the context/inherited aspects, then it makes sense.

I use `Positioned` for the scale bar, for example, which is now broken 🥲

**Comment by JaffaKetchup** [comment]
We've just implemented native polyline tappability on 'master', and I'm planning on hopefully implementing tappability on polygons. Hopefully sorting out those will remove the need for the current translucency workaround, and resolve this issue.
