### ISSUE TITLE
Compile error: No named parameter with the name 'layers'

### ISSUE THREAD

**Issue by team-boo** [fleaflet/flutter_map#1794]
### What is the bug?

```console
lib/main.dart:45:9: Error: No named parameter with the name 'layers'.
440.1         layers: [
440.1         ^^^^^^
440.1 /root/.pub-cache/hosted/pub.dev/flutter_map-6.1.0/lib/src/map/widget.dart:29:9: Context: Found this candidate, but the arguments don't match.
440.1   const FlutterMap({
440.1         ^^^^^^^^^^
466.2 Target kernel_snapshot failed: Exception
466.3 
466.9 
466.9 FAILURE: Build failed with an exception.
466.9 
466.9 * What went wrong:
466.9 Execution failed for task ':app:compileFlutterBuildRelease'.
466.9 > Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1
```

### How can we reproduce it?

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:geolocator/geolocator.dart';
import 'package:nfc_manager/nfc_manager.dart';
import 'package:disk_space_plus/disk_space_plus.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Map Example',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  MapSampleState createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  LatLng? _pickedLocation;

  @override
  void initState() {
    super.initState();
    // Add your NFC, storage checks, and location retrieval here
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Map Example'),
      ),
      body: FlutterMap(
        options: MapOptions(
          center: _pickedLocation ?? LatLng(51.5, -0.09),
          zoom: 13.0,
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            subdomains: ['a', 'b', 'c'],
          ),
          MarkerLayerOptions(
            markers: [
              Marker(
                point: _pickedLocation ?? LatLng(51.5, -0.09),
               child: Icon(Icons.location_on, size: 40.0, color: Colors.red),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

### Do you have a potential solution?

No i dont

### Platforms

LINUX

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by josxha** [comment]
May I ask what tutorial you followed along? Or did you used an AI like ChatGPT?

The bug is that there is "no named parameter with the name `layers`". Change the parameter name to `children` and you should be good to go.

I recommend to head over to the docs or the [example project](https://github.com/fleaflet/flutter_map/tree/ec81782c50ebc9191885f48d886f2e9e0fdead80/example/lib/pages).

**Comment by team-boo** [comment]
Hello,

Yes i used Chatgpt.

How you understood this?

when i move from "Layers:" to "children:" i have another error

"ib/main.dart:35:11: Error: The method 'TileLayerOptions' isn't defined for the class '_MapSampleState'.
442.9  - '_MapSampleState' is from 'package:new_project/main.dart' ('lib/main.dart').
442.9 Try correcting the name to the name of an existing method, or defining a method named 'TileLayerOptions'.
442.9           TileLayerOptions(
442.9           ^^^^^^^^^^^^^^^^
442.9 lib/main.dart:39:11: Error: The method 'MarkerLayerOptions' isn't defined for the class '_MapSampleState'.
442.9  - '_MapSampleState' is from 'package:new_project/main.dart' ('lib/main.dart')."

**Comment by team-boo** [comment]
Is unbelievable how useless is Chatgpt.

Is completely fake,hype whatever.

Cant create the simplest flutter app.

I have lost around one month doing cycles around very small tech issues that can be solve googling or asking on forums

in much less time.

Thank you.

**Comment by josxha** [comment]
Yes i agree, AIs like ChatGPT are large language models which means they are actually just trained to use language. Surprisingly they are able to reproducing stuff from the internet but all in all its more hyped than actually usefull in real world scenarious. 
If you get an answer you'd always have to check if it's correct - so you can just look it up yourself and are faster that way.
In this case literally everything the AI told you is either wrong or outdated (sometimes even since years).

I can recommend to start with the example project and copy stuff from there or modify it directly.
