### ISSUE TITLE
AnimateTo

### ISSUE THREAD

**Issue by ubatyrbekovfaq** [fleaflet/flutter_map#1842]
### What do you want implemented?

Can you add animate to ? I have use moveTo function but it doesn't work smoothly I used open-source solutions, but they also have freezes

https://github.com/fleaflet/flutter_map/assets/160235478/85cb27ed-ddbc-46ee-957f-5b998b2eb2dd

### What other alternatives are available?

flutter map animation is available but it doesn't work as supposed to be 

### Severity

Minimum: Not required for my use

**Comment by TesteurManiak** [comment]
Can you be a bit more precise? What is exactly the expected result for you to consider it "smooth"? What "open-source solutions" have you tried? (asking because I'm the maintainer of [flutter_map_animations](https://github.com/TesteurManiak/flutter_map_animations) and animating from point a to b has been working pretty well until now)
I don't think that an `animateTo` method is specifically needed in the core flutter_map repository to solve your issue.

**Comment by ibrierley** [comment]
You could use https://github.com/ibrierley/line_animator if any use.

**Comment by JaffaKetchup** [comment]
I'm closing this as it's been previously decided this form of animation is currently out of scope for FM core, and it is becoming more of a report of a bug in the existing animation plugin.
