### ISSUE TITLE
[BUG] v7-beta: `Polyline` becomes distorted & invisible (but remains interactive) when zoomed far in

### ISSUE THREAD

**Issue by RuoLiDevelop** [fleaflet/flutter_map#1864]
### What is the bug?

https://demo.fleaflet.dev/polyline
At zoom maximum
Hover over polyline while scrolling the mouse wheel
Display exception occurs

### How can we reproduce it?

![CF6D31E2-98B0-4E33-8150-01397AD5E816](https://github.com/fleaflet/flutter_map/assets/47424927/836f5d8c-ba51-453d-ae2f-52ffc0c9f580)

### Platforms

macOs chrome 

### Severity

Minimum: Allows normal functioning

**Comment by RuoLiDevelop** [comment]
[screen-capture.webm](https://github.com/fleaflet/flutter_map/assets/47424927/2f7addd5-c17d-41df-9e98-26b0e9941fdf)

**Comment by JaffaKetchup** [comment]
Hey @RuoLiDevelop,
Thanks for reporting this. I don't believe any exception occurs, as the polyline remains interactive the entire time, which means it is being painted, but there's definitely something strange going on: as you showed, it changes thickness, looks very strange, then disappears.
Zooming out does reintroduce the line correctly.
I can only assume there's some maths we're doing somewhere that doesn't like the precision required at this zoom level? Or the new code to cull polyline segments that are out of the viewport is not working quite right at this zoom level?

**Comment by RuoLiDevelop** [comment]
Hi @JaffaKetchup 
Thank you for your reply. I'm sorry, but for some reason, I haven't delved too deeply into the Flutter_map code. In theory, limiting the zoom level can solve this problem.

**Comment by JaffaKetchup** [comment]
No worries, no need to delve into the code unless you want to!

**Comment by monsieurtanuki** [comment]
> Or the new code to cull polyline segments that are out of the viewport is not working quite right at this zoom level?

@JaffaKetchup I've definitely noticed side-effects at high zoom levels, where segments are being dismissed.
@RuoLiDevelop Would you test with `cullingMargin: null`?

**Comment by RuoLiDevelop** [comment]
hi @monsieurtanuki 
I don't understand. ` cullingMargin: null`

**Comment by RuoLiDevelop** [comment]
I noticed minification zoom level,create line segments between unrelated polygons when the distance between polygons is long.

**Comment by RuoLiDevelop** [comment]
> I noticed minification zoom level,create line segments between unrelated polygons when the distance between polygons is long.

![Uploading lALPM3yRqDCmNgvNCJLNBHQ_1140_2194.png…]()

**Comment by RuoLiDevelop** [comment]
> I noticed minification zoom level,create line segments between unrelated polygons when the distance between polygons is long.

![lALPM3yRqDCmNgvNCJLNBHQ_1140_2194](https://github.com/fleaflet/flutter_map/assets/47424927/e66f6033-bb9d-463d-bf53-96c585642995)

**Comment by RuoLiDevelop** [comment]
v7-beta render with Impeller, I noticed minification zoom level,create line segments between unrelated polygons when the distance between polygons is long.

**Comment by RuoLiDevelop** [comment]
> v7-beta render with Impeller, I noticed minification zoom level,create line segments between unrelated polygons when the distance between polygons is long.

[screen-capture_1.webm](https://github.com/fleaflet/flutter_map/assets/47424927/43fccad4-9a16-4294-a315-591bead601ec)

**Comment by monsieurtanuki** [comment]
I've just run tests on the sample app, and added a FAB that increments the zoom while focusing on the same LatLng (`_mapController.move(const LatLng(48.8567, 2.3519), _zoom);`).
It works on any zoom level, even unreasonable ones (32), for dash style.
| zoom 19 | zoom 32 |
| -- | -- |
| ![Screenshot_1714548463](https://github.com/fleaflet/flutter_map/assets/11576431/b1911a08-dd8b-45a4-868e-a773f83933a9) | ![Screenshot_1714548372](https://github.com/fleaflet/flutter_map/assets/11576431/e960119d-95de-46dc-9dc1-64fc05e6f946) |

But it doesn't always work that well with solid style.
| zoom 19 | zoom 25 |
| -- | -- |
| ![Screenshot_1714548885](https://github.com/fleaflet/flutter_map/assets/11576431/d1b910c3-2b02-4a07-80eb-f3cca951f682) | ![Screenshot_1714549210](https://github.com/fleaflet/flutter_map/assets/11576431/077163b8-a38f-477c-af0c-07deff72ff76) |

@JaffaKetchup Would that mean that _dashed_ custom-made style is more resilient than _solid_ based-on-`Path` style?
In "extreme" zoom levels, that would make sense, as we deal with extreme coordinates (ignoring them) in the code before passing them (or not) to the `Path`.

**Comment by monsieurtanuki** [comment]
@JaffaKetchup Looks really like the `Path` doesn't like extreme coordinates.
I've just "fixed" the _solid_ style using a specific `SolidPixelHiker`, and as it limits the path segments to what is actually visible (i.e. with decent coordinates), it works perfectly on zoom 25 and even on unrealistic zoom 32.
| current zoom 25 | "my" zoom 25 | "my" zoom 32 |
| -- | -- | -- |
| ![Screenshot_1714549210](https://github.com/fleaflet/flutter_map/assets/11576431/077163b8-a38f-477c-af0c-07deff72ff76) | ![Screenshot_1714555249](https://github.com/fleaflet/flutter_map/assets/11576431/a010cfb6-cbc8-4fe0-8fe5-6cc0b585b82b) | ![Screenshot_1714555365](https://github.com/fleaflet/flutter_map/assets/11576431/466bff08-19bc-4bca-b692-92f9e7e19ea7) |

**Comment by JaffaKetchup** [comment]
@monsieurtanuki Wow, thanks for getting this fixed so quickly! We'd definitely appriciate a PR.

I'm a little bit confused what you were saying above. Do you mean that you think the issues are stemming from the new polyline segment culling that operates before painting, and you've moved it to painting, which seems to have fixed the issue? Or is there some issue with Flutter somewhere?

**Comment by monsieurtanuki** [comment]
@JaffaKetchup I said several things above, that go in different directions.

How to display correctly _solid_ style for polylines:
* As it looks like the _dashed_ and _dotted_ styles are displayed correctly, the fix is to find inspiration in them and apply it to _solid_ style.
* The _dashed_ and _dotted_ styles compute exactly the __visible__ segments / dots, and only them. The segment / dot coordinates used in the `path` are therefore relevant.
* The _solid_ style is currently dealt with differently, with a mere `path.addPolygon` and `canvas.drawPath`, with no coordinate preprocessing
* In my example above, the polyline is displayed correctly in zoom 24 with the current implementation, but not in zoom 25.
  * In zoom 24, the segment to display is `[Offset(196.4, 361.5), Offset(32560820.7, 55097704.0)]`
  * In zoom 25, the segment to display is `[Offset(196.4, 361.5), Offset(65121444.9, 110195046.5)]`
  * Therefore it could be that `path`s have problems with coordinates beyond 64M
=> Issue to open with flutter?
=> We can fix the polylines (the way I did), we cannot fix the polygons (and their area) that simply.
* As I come from Java, I'm a bit cautious with the performances, as we allocate again and again lists during the display when we precompute the coordinates
=> Who could test the performances of current and next _solid_ style display in a consistent way? I'd help if needed.
* I'll open a PR today for my "solid fix"

Beyond that, during my coding last month I experienced coordinate issues with polylines in big zoom situations. Something like some points were ignored while they were invisible but relevant.
I cannot say if the culling was wrong, or if I used it in an inappropriate manner (like, closing the polyline, which is not supposed to happen), or if I was in a phase of my coding that was unstable anyway.

**Comment by monsieurtanuki** [comment]
I confirm that polygon areas are not displayed correctly beyond the 64M limit.
And that cannot be solved with my fix. Other PRs are needed.

| zoom 24 | zoom 25 |
| -- | -- |
| ![Screenshot_1714578574](https://github.com/fleaflet/flutter_map/assets/11576431/9d96de46-8607-497d-abb4-e09bbb03d21e) | ![Screenshot_1714578584](https://github.com/fleaflet/flutter_map/assets/11576431/7b25f5ca-905a-4428-b22f-68431c3fe433) |

* zoom 24: `[Offset(196.4, 361.5), Offset(-60248650.4, 2244646.0), Offset(-37938681.4, 33140246.2)]`
* zoom 25: `[Offset(196.4, 361.5), Offset(-120497497.2, 4488930.6), Offset(-75877559.2, 66280131.0)]`

**Comment by monsieurtanuki** [comment]
By the way I fixed that "path with extreme coordinates" display side effect years ago for [osmdroid](https://github.com/osmdroid/osmdroid/) - including polygon areas - and I don't think it would be a problem to port the code from Java to dart/flutter:
* [LinearRing.java](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java)
* [SegmentClipper.java](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/SegmentClipper.java)
