### ISSUE TITLE
[BUG] MapEventTap - Delay between touch and event

### ISSUE THREAD

**Issue by QuentinSc** [fleaflet/flutter_map#1870]
### What is the bug?

There is a noticable delay between touch the map and the MapEventTap triggering.
This is not the case with MapEventMove which is instantaneous

### How can we reproduce it?
1. Listen to events
mapController.mapEventStream.listen((event) {...
2. Touch the map

### Platforms

Android 13,14 real devices and simulator

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hey @QuentinSc,
This is intentional to allow the double tap handler to determine whether it was a double tap or not. Depending on your version, you may be able to workaround the issue by disabling double tap zoom: https://docs.fleaflet.dev/usage/programmatic-control/listen-to-events#catching-specific-events.
