### ISSUE TITLE
[BUG] pub.dev score is about to drop

### ISSUE THREAD

**Issue by monsieurtanuki** [fleaflet/flutter_map#1972]
### What is the bug?

Having a look at https://pub.dev/packages/flutter_map/score, we see that though the score is maximum (160), there are pending issues that will decrease the score.
* Follow Dart file conventions - 10/10 points: Provide a valid pubspec.yaml
Issue tracker URL doesn't exist.
At the time of the analysis https://github.com/fleaflet/flutter_map/issues was unreachable. Make sure that the website is reachable via [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests.
* Platform support: 0/0 points: WASM compatibility
This package is not compatible with runtime wasm, and will not be rewarded full points in a future version of the scoring model.
See https://dart.dev/web/wasm for details.

### How can we reproduce it?

Just go to https://pub.dev/packages/flutter_map/score

### Platforms

Whatever

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
> Follow Dart file conventions - 10/10 points: Provide a valid pubspec.yaml (Issue tracker URL doesn't exist)

pana still assigns all the necessary points. I'm not sure why it doesn't detect it as a valid URL, whether it's GitHub refusing the requests from pub.dev for whatever reason (or whatever domain is running pana), or pana is broken. I might make an issue report to pana, as I've seen this before.

> Platform support: 0/0 points: WASM compatibility

This appears to be because we depend on https://pub.dev/packages/logger, which pana decides isn't Wasm compatible because it imports `dart:io` in a specific library. But due to platform dependent imports, this doesn't actually make it Wasm incompatible. The only solution here is for pana to get better at detection with these platform dependent import situations (which is also why packages manually define supported platforms, otherwise it would say we're not compatible with Web) (which I suppose is difficult to do statically?), or give us an option to label the package Wasm ready ourselves. See https://github.com/dart-lang/pana/issues/1324 & https://github.com/dart-lang/pub-dev/issues/6785.

Thanks for reporting this, I'm trying to keep an eye on it in general (https://github.com/dart-lang/pub-dev/issues/6785#issuecomment-2380885388).
