### ISSUE TITLE
ListView snatches scroll gestures

### ISSUE THREAD

**Issue by mulderpf** [fleaflet/flutter_map#253]
I put my map in a ListView.  When dragging left and right on the map, the maps scrolls around, when going up and down (the direction of the ListView), the ListView gets those gestures rather than the map.  How do I get the map to use those gestures instead?

**Comment by GregorySech** [comment]
I did a small experiment using a listview inside a listview and the behaviour works exactly as @mulderpf wants FlutterMap to work.
I'm wondering if this happens because FlutterMap is not a ScrollView.
While https://github.com/johnpryan/flutter_map/issues/174 is being implemented keep an eye to this issue too.

**Comment by buckettt** [comment]
@mulderpf Having the same issue here. Did you come up with a solution/workaround?

**Comment by AlexandrePhilibert** [comment]
This does not solve the issue but prevents the listView from picking up the vertical drag.

Wrap FlutterMap in a GestureDetector :
```dart
ListView(
    children: <Widget>[
        GestureDetector(
            onVerticalDragUpdate: (_) {},
            child: FlutterMap(
                ...
            ),
        ),
    ],
),
```

**Comment by brizaldi** [comment]
any update on this issue?

**Comment by sm2017** [comment]
@johnpryan I have same issue, Any solution?

**Comment by sm2017** [comment]
@mulderpf  Do you have temporary solution?

**Comment by kengu** [comment]
PR #994 fixes this problem
