### ISSUE TITLE
Handle rotation in plugins

### ISSUE THREAD

**Issue by moovida** [fleaflet/flutter_map#396]
I was wondering what the best practice would be in a plugin, to keep the graphics on screen even if the map rotates. For example the scalebar rotates with the map and therefore disappears.

I thought it would be simple as rotating back the drawing canvas of the same amount as the map.rotation, but it didn't work as expected.

Any hint? Thanks a ton.

**Comment by fluttercid** [comment]
I also want what you want.
There is any progress about it.
Thank you.

**Comment by moovida** [comment]
I assume this pull request will take care of it: https://github.com/fleaflet/flutter_map/pull/719

Well, most probably we will need a procedure that allows us to counter-rotate the plugins to have them kept right.

Also touch events will be an issue, if they are issued in plugins.

Most probably we will get (or we will implement :-) ) a rotation transformation from the map context to do this.

**Comment by maRci002** [comment]
#719 now implements this behavior: `able to mix rotate and non rotate layers with a flag`

Note: `onTap`, `onLongPress` still gives back the LatLng according to rotation.

I think I'll refactor to `specify separately non rotate and rotate layers so rotate layers will be always the bottom one` because rotating the whole layer tree is much faster than rotate one by one.

**Comment by maRci002** [comment]
PR updated now there are `layers` / `nonRotatedLayers` and `children` / `nonRotatedChildren` examples updated too.
