### ISSUE TITLE
[web] disappearing bits when loading PolylineLayerOptions

### ISSUE THREAD

**Issue by moovida** [fleaflet/flutter_map#446]
I hope it is ok to open this issue derived from #440, even if for the web version of flutter.
Currently I am finding this the only really blocking issue for the web and would like to share my findings and ask for suggestions or fix ideas.

Right now I am wondering if the issues is something in the Polyline painter. 

For example, this is a map with background and markers (one of which an image... nifty :-)):
![image](https://user-images.githubusercontent.com/390250/66843884-ad54cb80-ef6d-11e9-80c8-fe0d492463b8.png)

This is the same but lines instead of markers (background disappears):

![image](https://user-images.githubusercontent.com/390250/66843982-d4130200-ef6d-11e9-8e92-41248bf64b81.png)

This is background-lines-markers (background disappears, line is behind image):

![image](https://user-images.githubusercontent.com/390250/66844096-04f33700-ef6e-11e9-9288-1068e4d04f44.png)

And last but not least, same as before, but lines on top of markers, i.e. background-markers-lines:

![image](https://user-images.githubusercontent.com/390250/66844193-2fdd8b00-ef6e-11e9-9c97-0dd1840e54c0.png)

As you can see, the last one seems perfect...
but if I zoom in on the line:

![image](https://user-images.githubusercontent.com/390250/66844260-4be12c80-ef6e-11e9-927a-685d45ba58d8.png)

The image marker disappears, whereas the background remains.

If I then zoom even more, which makes the line to get out of the boundary of the image marker (which is fixed) and therefore overlay on the background map:

![image](https://user-images.githubusercontent.com/390250/66844355-7a5f0780-ef6e-11e9-8531-f5ed53c83981.png)

... the background disappears again.

The feeling is that whatever the line overlays directly, is "killed" by it.
I am sorry that I do not have a more code related report.

Any idea what might cause the issue?

**Comment by RBSoftwareBR** [comment]
Any solution?

**Comment by cfaigle** [comment]
My app works perfectly on Android, however for the web I see different results depending on the render engine as below, so that seems to point to underlying platform issues maybe.  Will anyone please run similar tests?  Thx

Separately the SKIA engine seems to work well for me except for the images so if they worked I would switch to that.

Android:
	All polylines render
	All marker render
	All map images show
![image](https://user-images.githubusercontent.com/8051559/77674370-ddaf8580-6f61-11ea-896e-23c7126c5a38.png)

Web, compiled normally:
	Only the final (last one in the list) polyline renders, the rest are missing.
	All marker render
	All map images show
![image](https://user-images.githubusercontent.com/8051559/77674199-91644580-6f61-11ea-8564-46dac5747691.png)

Web, compiled with '--dart-define=FLUTTER_WEB_USE_SKIA=true' :
	All polylines render (!)
	All marker render
	All map images missing
![image](https://user-images.githubusercontent.com/8051559/77674240-9de89e00-6f61-11ea-8bbe-12a59b04af60.png)

**Comment by moovida** [comment]
Hi @cfaigle , were you able to find the issue? I am struggling with this.
If I run:
```
flutter run -d web --dart-define=FLUTTER_WEB_USE_SKIA=true
```
I see also only the last polyline.
```
flutter run -d web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
```
then I see all the vector parts, but not the tiled background maps. 

It would be already good for me to understand if this is a bug in flutter_map or an issue with flutter in general.

**Comment by cfaigle** [comment]
Hi @moovida - I was not able to progress beyond that.  I believe the image support perhaps may not be implemented in SKIA for web, but I do not know why the compilers produce different output for the polylines.  It would seem most likely to be issue in flutter web javascript translator since the SKIA renderer and flutter on device works but not sure and I didn't find any similar issues opened there when I looked.  I would like a solution - this is the only blocker for me on flutter_map for web.

**Comment by moovida** [comment]
Same here @cfaigle , only blocker :-/

I tried to run it in --profile and saw the exception: Instance of 'ErrorSummary'
which seems to be causing the tiles to fail to load. 
Not sure what that means, but for now it is my only hook to hang on :-)
