### ISSUE TITLE
How about routing?

### ISSUE THREAD

**Issue by augusto3691** [fleaflet/flutter_map#461]
The leaflet has a pretty good routing machine with a way to calculate custom routes based on a GeoJson named pathfinder, there some roadmap for that ?

**Comment by ptv1p3r** [comment]
also would like to know that, how can i implement routing with this package?

**Comment by augusto3691** [comment]
After some research, you ll need to create a A* by yourself, if you use public routes i suggest move to google map implementation of flutter

**Comment by ibrierley** [comment]
I think it depends on what your goal is. You can certainly interface with a routing API like mapbox, and get directions and then draw them in flutter_map, that type of thing. But it's not clear really from the original issue what is needed, and that doesn't really need to be included as part of maps (i.e it's a separate entity really).

**Comment by ptv1p3r** [comment]
I would need to do the same as in google maps like so :
`List<PointLatLng> result = await polylinePoints.getRouteBetweenCoordinates(
        appSettings.getString("MAP_GOOGLE_KEY"),
        latitudeSource,
        longitudeSource,
        latitudeDestination,
        longitudeDestination
    );

    if(result.isNotEmpty){
      // loop through all PointLatLng points and convert them
      // to a list of LatLng, required by the Polyline
      result.forEach((PointLatLng point){
        polylineCoordinates.add(
            LatLng(point.latitude, point.longitude));
      });

      Polyline polyline = Polyline(
          polylineId: PolylineId('poly'),
          color: Color.fromARGB(255, 40, 122, 198),
          points: polylineCoordinates
      );

      globals.googlePolyLines.add(polyline);`

**Comment by JaffaKetchup** [comment]
I know this issue is closed, however I'd like to bring attention to http://project-osrm.org/. It's a free routing machine based on Open Street Maps. I'm currently in the process of making a plugin for this (or a separate package with extra support for `flutter_map`), but I'm quite busy at the moment, so there's no ETA.

**Comment by volethanh** [comment]
> I know this issue is closed, however I'd like to bring attention to http://project-osrm.org/. It's a free routing machine based on Open Street Maps. I'm currently in the process of making a plugin for this (or a separate package with extra support for `flutter_map`), but I'm quite busy at the moment, so there's no ETA.

I hope the plugin will be available soon

**Comment by JaffaKetchup** [comment]
@volethanh For now you can use the GitHub Experimental Alpha. Please don't use it in anything production-wise yet though.

https://github.com/JaffaKetchup/flutter_osrm

**Comment by volethanh** [comment]
> @volethanh For now you can use the GitHub Experimental Alpha. Please don't use it in anything production-wise yet though.
> 
> https://github.com/JaffaKetchup/flutter_osrm
> 
> Here's a small example line just for now:
> 
> ```dart
> import 'package:flutter_osrm/flutter_osrm.dart';
> 
> // Get a 'nearby' point
> OSRM(OSRMProfile.car).nearby(LatLng());
> 
> // Get a route between two points
> OSRM(OSRMProfile.car).route([LatLng(), LatLng()]);
> ```
> 
> apart from that, you'll have to figure it out yourself for now, as I'm not really dedicating my time to it at the moment (I'm maintaining another plugin for `flutter_map`, I am writing new docs for `flutter_map`, and I've got my own personal project).

May I ask something just about this osrm as you mentioned above ?

I use this `var osrmRoute = await OSRM(OSRMProfile.car).route(polylineCoordinates);` to get osRMRoute and then I use `nodesLocations` to simple create Polyline

<img width="1006" alt="Screen Shot 2021-08-13 at 11 28 02 PM" src="https://user-images.githubusercontent.com/46510130/129390862-852cf601-58b8-441f-bda8-d3e0bceceb01.png">
<img width="550" alt="Screen Shot 2021-08-13 at 11 28 10 PM" src="https://user-images.githubusercontent.com/46510130/129390877-267af36f-90b6-4cdf-80f2-f6d5eba3c06a.png">

Then add it to Widget 

<img width="289" alt="Screen Shot 2021-08-13 at 11 28 32 PM" src="https://user-images.githubusercontent.com/46510130/129390879-09bfe645-4a22-4256-a531-6795dd024d7b.png">

but the map cannot show the route instead of it show a line between 2 point. 

<img width="369" alt="Screen Shot 2021-08-13 at 11 32 26 PM" src="https://user-images.githubusercontent.com/46510130/129390882-46c50c7e-b937-4e4b-972c-9a1ca52ecd20.png">

Thanks for your help.

**Comment by JaffaKetchup** [comment]
Hi there, this should be drawing a route (it did in my testing), I think you're using it incorrectly, but I'll need to double check. Give me a bit of time and I'll be back.

Thanks,

Luka S


________________________________

**Comment by volethanh** [comment]
> Hi there, this should be drawing a route (it did in my testing), I think you're using it incorrectly, but I'll need to double check. Give me a bit of time and I'll be back. PS. Just to check whilst I'm checking, can you put your waypoints through `.nearby()` before using `.route()`?
> […](#)

Ah sorry, I found what make it wrong. 

Firstly, the api I've used is `OSRMRouteTrip` `var osrmRouteTrip = await osrmTrip(OSRMProfile.car, polylineCoordinates)` and it caused me an error when parsing returned value from api `.decodePolyline(apiResponse[0]["waypoints"]["location"])`

Secondly, I think the api [https://routing.openstreetmap.de](url) is the problem and it is only use for routing in Germany, I've changed it to my built api using OSRM project backend and I've changed to my api and it worked but it didn't draw a route.

 Currently, I don't know why the routing is a bit difference. 

this is my api link 
[http://routing.myownserver.com:5000/route/v1/driving/-122.084,37.4219983;10.0,10.0;105.848,21.6016;106.7368025,10.8273073?overview=false&alternatives=true&steps=true&hints=;;;](url)

And this this the link from routing.openstreetmap.de
[https://routing.openstreetmap.de/routed-car/trip/v1/car/-122.084,37.4219983;10.0,10.0;105.848,21.6016;106.7368025,10.8273073?overview=false](url)

After reversed all the code and use what you guide. Now it work

`OSRM(OSRMProfile.car).route([LatLng(), LatLng()]);`

thanks for your time to help me

**Comment by JaffaKetchup** [comment]
I set it to use the German routing because it supports car, walk and bike, and it routed correctly when I tested it in my local area in the United Kingdom, so not sure why that's a difference? But glad it works now!

If you don't mind, apart from the ability to change the routing server URL, what other options would you like to see, if any?

**Comment by thorizer** [comment]
@JaffaKetchup is it possible to add waypoints or only A to B ?

**Comment by JaffaKetchup** [comment]
Hi @thorizer,
You can route between as many waypoints as needed. Note that the more waypoints used the more expensive the processing becomes (time and power).
I am still very slowly working on this plugin in the background, and it has changed (only on my local device) significantly from the version on GitHub: please do not use this for serious projects at the moment.

**Comment by thorizer** [comment]
@JaffaKetchup, thanks can't wait! 
I switched from react native to flutter because of the availability of leafleat and osrm.

**Comment by JaffaKetchup** [comment]
Good to hear! Hope it all meets your expectations!

**Comment by nkdkhanh46** [comment]
You can use this package for the routing:

https://pub.dev/packages/flutter_map_directions

**Comment by aytunch** [comment]
> You can use this package for the routing:
> 
> https://pub.dev/packages/flutter_map_directions

@nkdkhanh46 Hi, can we see the github repo? In pub.dev it does not link to gh. Thanks

**Comment by JaffaKetchup** [comment]
(Also see https://github.com/fleaflet/flutter_map/issues/461#issuecomment-897599902. I still plan to work on it at some point!)
