### ISSUE TITLE
Infinite map/Repeat map at the left and right bounds

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#468]
It would be great if there were the possibility to scroll over 180°, repeating the world. 

Additionally, having this, one could draw lines from lon == 179° to lon == -179° , for example.

**Comment by znromonk** [comment]
@S-Man42 
I am trying to do the same and found a tentative workaround. It involves editing one of the files in the package, namely: `lib/src/geo/crs/crs.dart`

Replace
https://github.com/fleaflet/flutter_map/blob/95a8d26b353fc3cc62f29f210c2a91be8a5a2d5f/lib/src/geo/crs/crs.dart#L354-L355
with
```
    if (value.compareTo(start as num) < 0) return end as double;
    if (value.compareTo(end as num) > 0) return start as double;
```
What works:
- This forces the center of the map to slide over the+/-180 deg longitude wall when manually panned.

What doesn't work/ is buggy:
- If the map is slung into the boundary, it still does not flow through. It will hit that wall and will have to be manually panned over the boundary.
- If the map is centered in the negative longitude, any polylines/polygons on the positive side are not rendered. The same applies for the other way around.
- Polylines do not cross +/-180 boundary. It still takes the long way around.
- The map 'blinks' when you pass the +/-180 boundary.

Thoughts:
- This edit obviously doesn't allow the infinite panning to be optional. 
- It might be better to write an `_inclusive` function specifically for +/-180 since latitude does not need to be infinite. Technically it is being called by `inclusiveLat `and `inclusiveLng`.
