### ISSUE TITLE
package:latlong is deprecated

### ISSUE THREAD

**Issue by moovida** [fleaflet/flutter_map#485]
Hi, I am currently porting the JTS (Java Topology Suite) library to dart ( https://pub.dev/packages/dart_jts ). It already features the basics geometries with all the bells and whistles (overlay operations, distance ops, etc) as well as spatial indexes that can get in very handy for this library in future.
I would love to substitute the LatLont dependency, which is no longer developed and maintained, with that library.

Also, this would make it possible to have geopackage support integrated, which is an OGC standard and would also allow for an indexed offline vector format with attribute table for digital field mapping. ( https://pub.dev/packages/flutter_geopackage )

If you tell me that you would accept such a pull request, I would happily do the substitution and present the PR. 
Please let me know if it is of interest to the project.

**Comment by moovida** [comment]
BTW, regarding issue #484, the whole polygon, multipolygon and wholes part would be in there already.

**Comment by johnpryan** [comment]
Yeah if `package:latlng` is deprecated we will need to find a new package or find a new maintainer.

**Comment by moovida** [comment]
Well, from my part I can offer to make a pull request with a dependency to dart_jts. It is quite something more in functionalities than latlong was, but I think on the long run it is a win situation for the vector part. 
Being the port of a super-wellknown library, it also has already a ton of unit tests, which is good.

**Comment by Dev-Owl** [comment]
Just a quick question @moovida would `dart_jts` support LatLng for CRSSimple that are not in the range of -90 to 90 / -180 to 180 like the JavaScript version of Leaflet does? This would solve one issue I found while my checks (see #489) as my map is not a traditional map (plain image).

**Comment by moovida** [comment]
@Dev-Owl , well, the dart_jts is generic planar geometry and as such would allow to use coordinates in any CRS. But this doesn't mean that it would then be allowed by the flutter_map package. We would have to check. But it sure opens an interesting discussion :-)

BTW, just as info about JTS: https://locationtech.github.io/jts/

**Comment by synw** [comment]
What about creating a latlng2 minimalist package with the same api? It could contain only the necessary stuff. I use latlng everywhere in my geo stack and would like to replace it with a lightweight new conventional package. Because it is deprecated and also because it has no constant constructor. Basic features list:

- Latitude and longitude properties
- Constructor with validation
- Constant constructor

I made a [minimal implementation](https://gist.github.com/synw/847eb9051bb002d17c55ef0bec9a5cc0) that can be a starting point. Question: what are the features from LatLng that Flutter map uses internally, maybe unit conversions or something? What has to be kept from all the features of LatLng?

**Comment by fryette** [comment]
@moovida Is it possible somehow use https://pub.dev/packages/flutter_geopackage ?

**Comment by moovida** [comment]
Hi @fryette , I just answered you on the other issue :-)

**Comment by johnpryan** [comment]
There's now a fork of this package that has been upgraded to null safety: https://pub.dev/packages/latlong2
