### ISSUE TITLE
Tiles will not load after usage without a network

### ISSUE THREAD

**Issue by ristiisa** [fleaflet/flutter_map#576]
When the connectivity was lost and is restored the tiles that failed to load when the connectivity was lost will continue to fail to load:
`SocketException: Failed host lookup: 'a.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)`

Video of the issue:
https://streamable.com/9kaguw

Some time after the connectivity is restored an exception is caught:
![image](https://user-images.githubusercontent.com/514571/78667029-ec425900-78e0-11ea-8eef-2b99e578c984.png)

Tested with ac52f28716f799b2265da280e79ff56dc4950e1a
Flutter version 1.15.17
Framework revision 2294d75bfa (5 weeks ago), 2020-03-07 00:28:38 +0900
Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

**Comment by maRci002** [comment]
This seems serious bug however I tested this against `0.8.2 release` and it behaves same way.
`git checkout 031fa41544f34a91acf69d0c3b758514f1ea2f5c` or if you are using it as dependency `flutter_map: 0.8.2` (**not ^0.8.2**) then `flutter pub upgrade`.

Here is a fast 0.8.2 preview:
![0 8 2 release](https://user-images.githubusercontent.com/8436039/78691006-70540b00-78f8-11ea-81b9-2796f53246d6.gif)

I think I know how to fix this issue, give me some time and I will make a new PR, the main problem is within flutter because it caches the failed Image, see:
```
/// Fetches the given URL from the network, associating it with the given scale.
///
/// The image will be cached regardless of cache headers from the server.
///
/// When a network image is used on the Web platform, the [cacheWidth] and
/// [cacheHeight] parameters of the [DecoderCallback] are ignored as the Web
/// engine delegates image decoding of network images to the Web, which does
/// not support custom decode sizes.
///
/// See also:
///
///  * [Image.network] for a shorthand of an [Image] widget backed by [NetworkImage].
// TODO(ianh): Find some way to honor cache headers to the extent that when the
// last reference to an image is released, we proactively evict the image from
// our cache if the headers describe the image as having expired at that point.
abstract class NetworkImage extends ImageProvider<NetworkImage> {
```

**Comment by maRci002** [comment]
@ristiisa take a test ride with #577 don't forget to provide `evictErrorTiles` flag to `TileLayerOptions` since error tiles will become active they will be retained too, however _pruneTiles will have chance to evict error tiles if they are not retained anymore.

**Comment by maRci002** [comment]
`Some time after the connectivity is restored an exception is caught:` it was because they were not retained anymore, forinstance if error happened on zoom lvl 5 and you changed zoom zo lvl 7 or if overpanning the [default 2 tiles margin](https://github.com/johnpryan/flutter_map/pull/572#issuecomment-610321375).

**Comment by ristiisa** [comment]
> @ristiisa take a test ride with #577 don't forget to provide `evictErrorTiles` flag to `TileLayerOptions` since error tiles will become active they will be retained too, however _pruneTiles will have chance to evict error tiles if they are not retained anymore.

I'm not sure if I'm seeing any changes in the behavior.

![image](https://user-images.githubusercontent.com/514571/78897201-7a057c00-7a7a-11ea-824a-b1f37f1d0b15.png)

**Comment by maRci002** [comment]
It's because `_pruneTiles` / `_abortLoading` wasn't called, I have seen your video and map was moved by a MapController which took small steps and error tiles was still retained. I think I can make `evictErrorTiles` even stricter forinstance if error Tile is not in viewport / not on same zoom lvl as mapState.zoom then evict an error tile may seem fair enough. So I think `evictErrorTiles` will be better `evictErrorTilesStrategy` enum which will support/allow this behaviour.

```
  // If a Tile was loaded with error and if this flag is true, then TileProvider
  // will be asked to evict Image during _pruneTiles / _abortLoading calls
  // (see #576 - even Error Images are cached in flutter)
  final bool evictErrorTiles;
```

Anyway if you are moving map by a controller then #579 contains some fix.

**Comment by maRci002** [comment]
@ristiisa I updated the PR with more strategy like `EvictErrorTileStrategy.notVisible`.

![evict not visible](https://user-images.githubusercontent.com/8436039/78950479-2709e400-7acf-11ea-95cf-2a216867bfd4.gif)
