### ISSUE TITLE
Polygon clipping

### ISSUE THREAD

**Issue by adnanefouam** [fleaflet/flutter_map#624]
i want to check  the intersection coordinates of these two polygones and  cliping the blue polygon inside the grey one is there a solution for this or any idea ? 

<img width="448" alt="Screen Shot 2020-05-22 at 23 32 18" src="https://user-images.githubusercontent.com/59290932/82715900-9b19d900-9c84-11ea-996f-50f3a0e06f0a.png">

**Comment by moovida** [comment]
There is an ongoing effort to bring the jts library (which is the top for operations like these) here: https://pub.dev/packages/dart_jts
Intersection itself is not yet ported, but the whole base is, so it should not be too hard to bring in the classes from java. Then you would have the polygon clip done.

**Comment by maRci002** [comment]
Since Polygons are just canvases you can play with [BlendMode](https://api.flutter.dev/flutter/dart-ui/BlendMode-class.html), however you will need to modify a little bit `PolygonPainter`. See [polygon_layer.dart](https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/polygon_layer.dart) when I needed to cut holes in polygon I played a bit with canvas.

**Comment by adnanefouam** [comment]
i notice that the stack widget is the parent of. the polygones why not using just overflow: Overflow.clip, ? 
<img width="1259" alt="Screen Shot 2020-05-25 at 19 14 31" src="https://user-images.githubusercontent.com/59290932/82838650-c4c14300-9ec4-11ea-99f9-c2133350b424.png">

**Comment by mohammedX6** [comment]
I have ported a libary that capable of doing all polygon Boolean operations on polygons (union, intersection, difference, xor) ( [More info here](https://pub.dev/packages/poly_bool_dart)
