### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#63]
- [ ] MapController https://github.com/apptreesoftware/flutter_map/issues/58
- [ ] Plugin API
- [ ] Code comments
- [ ] feature roadmap
- [ ] Layer types (MBTiles, etc)

**Comment by neiljaywarner** [comment]
how can you use mapbox styles - or can you?

**Comment by GregorySech** [comment]
@johnpryan I'm starting to study the project to try and contribute a little. 
Can I open a PR for possible comment improvements? 
Do you need help for some specific area?
I'm wondering if some files should me moved, for example the TileProviders could get their own place instead of being all in tile_layers.dart except for MBTilesImageProvider.

**Comment by JaffaKetchup** [comment]
Replaced by #992.
