### ISSUE TITLE
Markers below CircleLayerOptions don't trigger onTap events 

### ISSUE THREAD

**Issue by HugoHeneault** [fleaflet/flutter_map#650]
I have a map with markers and circle layer. 

```dart
FlutterMap(
              layers: [
                TileLayerOptions(),
                MarkerLayerOptions(
                  markers: widget.markers,
                ),
                if (currentLocation != null)
                  CircleLayerOptions(
                      circles: getCurrentLocationCircles(currentLocation)),
                if (currentLocation != null)
```

When `CircleLayerOptions` isn't rendered, I can tap my markers. When it is rendered, marker's `GestureDetector` won't trigger `onTap` events anymore. 

How can I fix that?

Thanks!

**Comment by ibrierley** [comment]
It's not clear if circle layer has any events on it. But if not, you could just add the circlelayeroptions code before the markerlayeroptions ?

**Comment by HugoHeneault** [comment]
Thanks @ibrierley for your reply :)

I can't put the circles before the markers, as I need circles to be on foreground. 🙈

**Comment by ibrierley** [comment]
Just thinking out loud...

Do you need events on both, if not then I wonder if you could have an ignorePointer over the circle...eg https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html

Rather than the circle layer, could you have a marker layer, but with a circle icon as the marker and ignorepointer on. 

You may need to describe a bit better if both have events on them, it may be more fiddly depending on the specific interactions of what happens when a marker and a circle overlay and events etc.

**Comment by HugoHeneault** [comment]
Sorry I missed your question about events. 

I don't need events on circles (yet?). But I need to calculate circles radiuses in meters. 
Why isn't CircleLayer working like MarkerLayer about events? :)

**Comment by ibrierley** [comment]
Someone with better flutter understanding may have a good answer to that one. I was wondering if it was that circlelayer uses canvas I think, that may intercept events, but I'm purely guessing here.

**Comment by MooNag** [comment]
From my knowledge and testing of this issue, it seems like any flutter_map layer completely blocks touch events from all layers below it. This means you cannot have 2 sets of MarkerLayers with gesturedetectors, you have to put all the markers on one layer. This also means you cannot have tappable polys and markers on the same map at the same time. I could not find a way in flutter_map to stop the layer from intercepting all touch events. You could get around it by only using touch events from the map itself and getting the marker/circle/poly/whatever that is closest to that set of cords, but that is just getting around the problem because ideally you use a gesturedetector of some sort on each layer, and the layers objects above block the ones below, but not the layer itself.
