### ISSUE TITLE
Handle Tile not found error

### ISSUE THREAD

**Issue by sn4k3ch4rm3r** [fleaflet/flutter_map#669]
Is there a way to disable or manually handle the excteption thrown when I use a tileset with a small area covered?

**Comment by chipscal** [comment]
Has anyone found a solution for the problem?

In my use case I have two tile sources, the first from mapbox (that it works correctly) and another one from my own tile server that show raster products over the mapbox map. I'm using a slightly modified version of the NetworkImageWithRetry tile provider. I just added the possibility to append custom headers in order to sent a JWT access token in the Authorization header.

The problem is that for my application is perfectly normal to receive "404 Not found" errors as the product rasters are not generated worldwide but just where necessary, so in general the entire view of the map will not be filled entirely by the raster.

The problem is that whenever I receive a 404 the map does not show anything. Do yow have any suggestion?

P.s. the tile server works fine, it is already in production and used from a web implementation using mapbox-gljs.

Thanks for the help!
