### ISSUE TITLE
Vector Tile Plugin proof of concept...

### ISSUE THREAD

**Issue by ibrierley** [fleaflet/flutter_map#716]
Just for anyone looking into this, I've uploaded the code I've been fiddling with at  https://github.com/ibrierley/flutter_map_vector_tiles

It currently "works", but it's a proof of concept, there are working vector tiles :). But mileage will vary, initial issues are mentioned on the readme there. Custom styling is not supported yet, just a default one, but I'm looking for suggestions a bit on that (may be good to support mapbox spec)

Hopefully some may have a play and find useful as a starting point, and feedback any thoughts (and code!). It's not documented yet, but I'll try and get round to some of that when I think it won't change too much.

It would be good if anyone else wants to get involved, as it's not a trivial project :).

**Comment by moovida** [comment]
Great stuff you have here, thanks a lot, will sure take it for a testride. I still have your geometries editor project in my tasklist. :-D 

BTW, even if you think the png generation is not so nice, think that the space saved with vector tiles also for offline use are amazing! I think I have a vector tiles mbtiles database somewhere, covering half of Europe in around 8 giga (i think, going by memory). I am missing it since my last computer break, but if I am able to recover it, I will test that and share it if there is interest.

**Comment by Cajuteq** [comment]
how does it compares to https://github.com/greensopinion/flutter-vector-map-tiles ? are both projects concurrents ? (maybe you could join forces)

**Comment by ibrierley** [comment]
Heya, I would certainly go for the one you have linked. It's a lot better written and further developed supporting mapbox styles etc (and works!). Just be aware that all vector tiles in Flutter typically have a bit of a performance hit due to various issues compared to raster tiles, so you may want to think about how its used and give it a test run.

I'm still fluffing around with some ideas, and may be interesting for someone wanting to start something more from scratch that doesn't need to support the normal mapbox styles etc, but I wouldn't recommend my stuff atm :).
