### ISSUE TITLE
How can I rotate only 'TileLayerOptions'

### ISSUE THREAD

**Issue by fluttercid** [fleaflet/flutter_map#723]
I have 3 layers such as TileLayerOptions, ZoomButtonsPluginOption and ScaleLayerPluginOption.
When I appled the rotation function, all layers are rotated.
I want to rotate only TileLayerOptions layer.
Is there any solution for this?
Thank you for your help in advance.

before:
![image](https://user-images.githubusercontent.com/65621167/89681352-2e999800-d8cb-11ea-9d4a-90472968487b.png)

after:
![image](https://user-images.githubusercontent.com/65621167/89681412-4a04a300-d8cb-11ea-9569-c79cdf632f0d.png)

**Comment by maRci002** [comment]
I'll add this feature in #719.
You are right not all plugins should rotate.

There are two ways to go:
- specify separately non rotate and rotate layers so rotate layers will be always the bottom one
- able to mix rotate and non rotate layers with a flag

**Comment by fluttercid** [comment]
Thank you so much.
I will try it.

**Comment by maRci002** [comment]
#719 now implements this behavior: `able to mix rotate and non rotate layers with a flag`

Note: `onTap`, `onLongPress` still gives back the LatLng according to rotation.

I think I'll refactor to `specify separately non rotate and rotate layers so rotate layers will be always the bottom one` because rotating the whole layer tree is much faster than rotate one by one.

**Comment by maRci002** [comment]
PR updated now there are `layers` / `nonRotatedLayers` and `children` / `nonRotatedChildren` examples updated too.
