### ISSUE TITLE
Load tiles beyond maxNativeZoom if available

### ISSUE THREAD

**Issue by Swepilot** [fleaflet/flutter_map#767]
I have created a MBTiles file with worldwide tiles zoom 0-7 and merged with another MBTiles database containing zoom 8 for limited areas. If I set `maxNativeZoom` to 7 the areas where z8 is available never gets loaded with the z8 (naturally). If I set `maxNativeZoom` to 8 it gets loaded but then the areas outside the z8 area loses all tiles when zooming past z7.

So what I am trying to achieve is to have tiles loaded as long as they are available and if not available initially revert to the tiles from `maxNativeZoom` and as last resort throw the error.

Has anyone experimented with this that could point me in the right direction?

**Comment by maRci002** [comment]
There isn't any option to support this kind of behaviour however you can edit `tile_layer.dart` to support this feature.

I think you can achieve this with current implementation if you use two different layer instead of the merged one.
Layer 1: `zoom`: 0-8 and `maxNativeZoom`: 7
Layer 2: `zoom`: 8-8

**Comment by Swepilot** [comment]
Thanks, I'll get back on this task in a little while. Right now I'm trying to modify/create a custom TileProvider for modified caching behaviour...
