### ISSUE TITLE
Draw features

### ISSUE THREAD

**Issue by AlirezaAsadi96** [fleaflet/flutter_map#790]
How can I draw Polygon/Line/Point when I tap on map?

**Comment by ibrierley** [comment]
Create a polyline layer, that builds a list with polylines in it, which is added to the map.

Then with an onTap in your MapOptions, add the polyline you just created to that polyline list. Next build call, it should all be displayed for you.

If you get stuck, show us a minimal example of what you have with the problem, and I'm sure someone will takea look.

**Comment by AlirezaAsadi96** [comment]
> Create a polyline layer, that builds a list with polylines in it, which is added to the map.
> 
> Then with an onTap in your MapOptions, add the polyline you just created to that polyline list. Next build call, it should all be displayed for you.
> 
> If you get stuck, show us a minimal example of what you have with the problem, and I'm sure someone will takea look.

Ok. I will try and announce the answer.
Thank you so much

**Comment by AlirezaAsadi96** [comment]
Ok. I will try and announce the answer.
Thank you so much

**Comment by prl900** [comment]
I have tried this approach and it works well, I have managed to implement the polygon drawing functionality using the `onTap`. Users can create polygons interactively by clicking on the screen. This gets visualised using `PolylineLayerOptions`. When users close the polygon by clicking on the first point the result gets visualised using `PolygonLayerOptions`.

However, I'm having trouble determining when the first point of the polygon gets clicked for closing it. I have implemented an approach in which every tapped LatLon position gets compared to the initial one using a threshold. The problem is that this threshold should be dependent on the zoom level, to allow users drawing polygons of any size. Ideally, this should be done using screen pixel positions rather than LatLon values, although I'm not sure if this is possible.

I reckon I could use the zoom level information to work out the relative distance between tapped points in the screen, although I'm not about the best approach for this.

I'd appreciate if anyone has a suggestion for coding a robust polygon drawing functionality.
