### ISSUE TITLE
How to replace CachedNetworkTileProvider

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#832]
Hi,

currently I am using the CachedNetworkTileProvider, which was removed here: https://github.com/fleaflet/flutter_map/commit/1a6b495554f2e61e841874aff21621852cbeed9b

So, when updating to 0.11.0, how can I replace the CachedNetworkTileProvider properly to keep the caching functionality?

Kind regards!

**Comment by Swepilot** [comment]
Wow, his has been removed? What's the reason for that? My app heavily relies on that provider.

**Comment by rorystephenson** [comment]
I also didn't notice this removal.

Having a look at the other tile providers it seems like `NetworkTileProvider` _should_ provide the same functionality. It uses [`NetworkImageWithRetry`](https://pub.dev/documentation/flutter_image/latest/network/NetworkImageWithRetry-class.html) and the document indicates that this caches all images but when I tried a naive test it doesn't seem to do so.

I loaded some tiles, turned off internet in the emulator, restarted the app and the loaded tiles did not load without internet.

So I tried copying the old `CachedNetworkTileProvider` which _does_ work in my test. So as a workaround you can add the old code to your project and use that as the tile provider:

```dart
class CachedNetworkTileProvider extends TileProvider {
  const CachedNetworkTileProvider();

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return CachedNetworkImageProvider(getTileUrl(coords, options));
  }
}
```

---

I think the removal of this code makes sense given that it uses `cached_network_provider` which in turn has `sqflite` as a dependency. If you don't need caching it's a shame to have `sqflite` as a dependency for no reason.

**Comment by MooNag** [comment]
I believe disk caching was removed to get rid of the largest and slowest updating dependencies iirc. However this is not a bad thing. It should allow for more updates and less monolithic code.
Here are 2 ways to implement tile caching that could be added to the readme. I will look at making a pr for it.

1. Ram caching
Create a new TileProvider. This is a built in Flutter image provider and will cache the tile images until the next app restart. This does not store images on disk or requires any extra dependencies.

```dart
class CachedNetworkTileProvider extends TileProvider {
  const CachedNetworkTileProvider();

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return ImageProvider(getTileUrl(coords, options));
  }
}
```

2. Disk cache (requires a cache dependency or custom imageprovider)
Same code as above; except instead of using the built in flutter imageProvider we will use a custom image provider or dependency. In this case we will use `cached_network_image`. 

```dart
import 'package:cached_network_image/cached_network_image.dart';

class CachedNetworkTileProvider extends TileProvider {
  const CachedNetworkTileProvider();

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return CachedNetworkImageProvider(getTileUrl(coords, options));
  }
}
```

**Comment by S-Man42** [comment]
For me, both solutions don't work:

The first one doesn't cache the tiles, the second one doesn't even load the tiles anymore. :(
