### ISSUE TITLE
Updating dart package request

### ISSUE THREAD

**Issue by altec-icex** [fleaflet/flutter_map#876]
Hi, John.

Please update pub.dev/packages/flutter_map repository for latest changes in git because your current version in pub.dev doesn't work with old version of latlong in compare to your git version.

Thanx

**Comment by josxha** [comment]
Hello @altec-icex, I have used the `1.12.0` version on `pub.dev` myself and it worked just fine. What makes you think that version doesn't work?

**Comment by altec-icex** [comment]
"flutter_map 0.12.0"
see in pubspec.yaml at dependencies section

PUBDEV - latlong: ^0.6.1
GITHUB - latlong2: ^0.8.0

**Comment by kengu** [comment]
@altec-icex This is to be expected, since released versions on pub.dev is lagging the master branch. @johnpryan will release a new version at some point, usually after som substantial changes merged to master. I guess the reason for 0.13.0 is not yet released to pub.dev is that we are waiting on `flutter_image` to upgrade to sound null-safety. At this point #870 will be merged to master and 0.13.0 will be released with dependency `latlong2: ^0.8.0` (the switch to  latlong2 is due to lack of maintenance of latlong).
