### ISSUE TITLE
move a marker on a polyline

### ISSUE THREAD

**Issue by X-SLAYER** [fleaflet/flutter_map#879]
is thre any alternative to [LeafletPlayback](https://github.com/hallahan/LeafletPlayback) or any way to make a marker move on polyline

**Comment by ibrierley** [comment]
No replies on this one, but I kind of like this idea and may come back to it at some point. Not sure if it needs some interface/widget for it, or just a function that provides a latlng at a certain interpolated time.

**Comment by X-SLAYER** [comment]
there is an implementation in android (java) I think might help 
[How to move marker along polyline using google map](https://stackoverflow.com/questions/40526350/how-to-move-marker-along-polyline-using-google-map/40686476)

**Comment by ibrierley** [comment]
I don't think the basics should be "too" difficult really. It's more understanding how it would be used on mobile...how would one interact with it, to get it to play in reverse...or does it simply need a time and a marker position (eg play the whole route for 10 seconds at an even pace), does it need a widget etc.

If you are reversing the route, should any pointed marker point in reverse. The leaflet example I think is quite different in some ways (visually at least) to the Stackoverflow question.

Devil is often in the detail :).

**Comment by X-SLAYER** [comment]
yes I got your point

**Comment by ibrierley** [comment]
Btw if interested, I've just added some bits to https://github.com/ibrierley/line_animator  it basically just interpolates points (can step through them, or interpolate between them also, and also reverse them). The basic interpolator also returns an angle as well, so if one thinks of that as a heading, you can rotate a marker or whatever. I did add some code to set the begin distance, but I haven't tested that. I may get it to work on interpolating time rather than distance, but they are kind of two sides of the same coin given any duration.
There's an example in example/lib that moves a plane down a polyline, and draws it, but simply don't include the polyline if you don't need it. 
I've run out of time for a few days to test it properly and develop it further (it may be nice to smooth out heading on sharp turns animation wise, but that's for another day. Maybe it can help someone though.

**Comment by X-SLAYER** [comment]
nice work i will test it and give u my feedback

**Comment by ibrierley** [comment]
No worries, it was a bit of a rush job as I'm away now a few days, but feel
free to make a list of any issues.

**Comment by mohammedX6** [comment]
Hi @ibrierley, I don't want to make this method automatic, I want to move the marker manually along a line, do you have any ideas?

**Comment by ibrierley** [comment]
what do you mean by manually...the devil is in the detail.

**Comment by mohammedX6** [comment]
@ibrierley If you could please see this https://youtu.be/k6gUhuHZxwU?t=204 , That's what i mean.

**Comment by ibrierley** [comment]
I did an answer for javascript on a similar problem a long time ago....   http://jsfiddle.net/ian_b/kKLtH/332/

You could ake a look at converting that (you would probably have to figure out a getPointAtLength method for that, there may be something in pathMetrics class or similar, or roll your own). There is similar in https://api.dart.dev/be/169657/dart-svg/GeometryElement/getPointAtLength.html that one could possibly copy as well.

**Comment by ibrierley** [comment]
Ooops original question/answer... https://stackoverflow.com/questions/35612003/drag-object-through-specific-path-and-move-in-a-sibling-path/35625792#35625792
