### ISSUE TITLE
Update tuple dependency

### ISSUE THREAD

**Issue by DenisBarzanov** [fleaflet/flutter_map#899]
Because flutter_map >=0.5.0+1 depends on tuple ^1.0.2 which depends on quiver >=0.22.0 <3.0.0, flutter_map >=0.5.0+1 requires quiver >=0.22.0 <3.0.0.

And because google_sign_in >=5.0.1 depends on google_sign_in_platform_interface ^2.0.1 which depends on quiver ^3.0.0, flutter_map >=0.5.0+1 is incompatible with google_sign_in >=5.0.1.
So, because APP depends on both google_sign_in ^5.0.2 and flutter_map ^0.12.0, version solving failed.
pub get failed (1; So, because revolv depends on both google_sign_in ^5.0.2 and flutter_map ^0.12.0, version solving failed.)

**Comment by kengu** [comment]
Package tuple is updated in branch [issues/829-nullsafety](https://github.com/fleaflet/flutter_map/tree/issues/829-nullsafety) which we hope to merge to master soon.

**Comment by williamborba** [comment]
I have same problem, problable relation with "quiver" package

```
Because flutter_html >=2.0.0-nullsafety.1 depends on flutter_layout_grid ^1.0.1 which depends on quiver ^3.0.0, flutter_html >=2.0.0-nullsafety.1 requires quiver ^3.0.0.
And because flutter_map >=0.5.0+1 depends on tuple ^1.0.2 which depends on quiver >=0.22.0 <3.0.0, flutter_html >=2.0.0-nullsafety.1 is incompatible with flutter_map >=0.5.0+1.
So, because petscarentes depends on both flutter_map 0.12.0 and flutter_html 2.0.0, version solving failed.
pub get failed (1; So, because petscarentes depends on both flutter_map 0.12.0 and flutter_html 2.0.0, version solving failed.)
```

**Comment by ChristianGiupponi** [comment]
Same for me with `flutter_html`, hope to see it merged soon.

**Comment by mma-amini** [comment]
Because flutter_map >=0.1.1 depends on latlong ^0.6.1 which depends on logging >=0.11.3 <1.0.0, flutter_map >=0.1.1 requires logging >=0.11.3 <1.0.0.
And because lottie 1.0.1 depends on logging ^1.0.0 and no versions of lottie match >1.0.1 <2.0.0, flutter_map >=0.1.1 is incompatible with lottie ^1.0.1.
So, because sesoot depends on both lottie ^1.0.1 and flutter_map ^0.12.0, version solving failed.
pub get failed (1; So, because sesoot depends on both lottie ^1.0.1 and flutter_map ^0.12.0, version solving failed.)
