### ISSUE TITLE
LateInitializationError on PolylineLayerOptions

### ISSUE THREAD

**Issue by Uraskin** [fleaflet/flutter_map#931]
Hello! Found an error when working with PolylineLayerOptions constructor :
`if (polylineCulling) {
      for (var polyline in polylines) {
        polyline.boundingBox = LatLngBounds.fromPoints(polyline.points);        
      }
 }`
    
Here if we reuse exist polylines item (when we refresh map and call setState), then we will face with LateInitializationError, because boundingBox has a late init and its was initialized before.

**Comment by mblataric** [comment]
Just ran into this myself. 
Is there any workaround?

**Comment by ibrierley** [comment]
Not sure if I'm misunderstanding a bit (quite possible!), why are you reusing it, rather than creating a new widget ? Maybe an example would be useful to highlight the problem (and for anyone to test a fix).

**Comment by mblataric** [comment]
> Not sure if I'm misunderstanding a bit (quite possible!), why are you reusing it, rather than creating a new widget ? Maybe an example would be useful to highlight the problem (and for anyone to test a fix).

Not sure what you mean "reusing it"? Reusing what? 

For me, I get this error as soon as I add this to flutter map layers:

`            PolylineLayerOptions(
                polylineCulling: false, polylines: [kartaModel.polyline])`

**Comment by ibrierley** [comment]
Sorry, I was reading from the original problem that was raised, it was talking about reusing the polylines, so I'm guessing your problem is a bit different then.

I use PolylineLayerOptions and don't get any lateinit error (and I'm assuming the polyline example doesn't give that error, but I haven't tested that yet), so wondering what's different in your case. 

Seeing a minimal example reproducing the error as ever would be useful.
