### ISSUE TITLE
TileLoader failed to load tile due to mWriter being null (map shutdown?)

### ISSUE THREAD

**Issue by jesussmile** [fleaflet/flutter_map#962]
Hey! I have a simple implementation of flutter map, It has a Textfield which when pressed goes to another page where I can search for a location,  However, as soon as the keyboard pops up The map on the previous page shuts down

`TileLoader failed to load tile due to writer being null (map shutdown?)`
How do I handle this behavior? I tried almost everything, is it because the widget is getting rebuilt? How do I preserve my map state?

**Comment by ibrierley** [comment]
I'd suspect it's not because it's not being built, rather that its been removed from the widget tree, when you navigated away. My own preference has to use an Offstate() widget, so that the map preserves state during navigation. But assuming you're using a mapcontroller, it can sometimes be quite fiddly to get it right if you do need to remove it from the tree (there's a couple of threads related to that).

**Comment by jesussmile** [comment]
As per your advice, I tried to work with Visibility() but no luck, wonder what should be done!

**Comment by jesussmile** [comment]
Well thank you!  It worked with offstage!
